using ApiV3.Models;
using ApiV3.Models.NoMapeado;
using Microsoft.AspNet.OData.Builder;
using Microsoft.OData.Edm;
using System;
using System.Linq;

namespace ApiV3.Support.Configuration
{
    public static class OdataEdm
    {

        public static IEdmModel GetEdmModel(IServiceProvider serviceProvider)
        {
            var builder = new ODataConventionModelBuilder(serviceProvider);
            builder.EnableLowerCamelCase();
            builder.EntitySet<Actividad>("Actividades")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Candidato>("Candidatos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ActividadCentroCosto>("ActividadCentroCostos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ActividadFuncionario>("ActividadFuncionarios")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ActividadFuncionarioDatoActual>("ActividadFuncionarioDatoActuales")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<LibroVacacionesConsolidado>("LibroVacacionesConsolidados")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ActividadFuncionarioCentroCosto>("ActividadFuncionarioCentroCostos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<AnnoVigencia>("AnnoVigencias")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<AplicacionExterna>("AplicacionExternas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<AplicacionExternaCargo>("AplicacionExternaCargos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<AplicacionExternaCargoDependiente>("AplicacionExternaCargoDependientes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<AusentismoFuncionario>("AusentismoFuncionarios")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Beneficio>("Beneficios")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<BeneficioAdjunto>("BeneficioAdjuntos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<BeneficioSubperiodo>("BeneficioSubPeriodos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CentroTrabajo>("CentroTrabajos")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CargoDependencia>("CargoDependencias")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CargoGrado>("CargoGrados")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CargoGrupo>("CargoGrupos")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<CargoPresupuesto>("CargoPresupuestos")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<CargoReporta>("CargoReportas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Cargo>("Cargos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CargoCentroCosto>("CargoCentroCostos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CategoriaNovedad>("CategoriaNovedades")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CategoriaParametro>("CategoriaParametros")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CausalTerminacion>("CausalTerminaciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ConceptoBase>("ConceptoBases")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ConceptoNomina>("ConceptoNominas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ConceptoNominaTipoAdministradora>("ConceptoNominaTipoAdministradoras")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ContratoCentroTrabajo>("ContratoCentroTrabajos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ClaseAportanteTipoAportante>("ClaseAportanteTipoAportantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CuentaBancaria>("CuentaBancarias")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<DeduccionRetefuente>("DeduccionRetefuentes")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAusentismoConceptoNomina>("TipoAusentismoConceptoNominas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ConceptoNominaCuentaContable>("ConceptoNominaCuentaContables")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Contrato>("Contratos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ContratoAdministradora>("ContratoAdministradoras")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ContratoAdministradoraCambio>("ContratoAdministradoraCambios")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ContratoCentroTrabajoCambio>("ContratoCentroTrabajoCambios")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CentroCosto>("CentroCostos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CentroOperativo>("CentroOperativos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ClaseAusentismo>("ClaseAusentismos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ClaseLibretaMilitar>("ClaseLibretaMilitares")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<CuentaContable>("CuentaContables")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<DocumentoFuncionario>("DocumentoFuncionarios")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Embargo>("Embargos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<EmbargoConceptoNomina>("EmbargoConceptoNominas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<EmbargoSubperiodo>("EmbargoSubperiodos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<EstadoCivil>("EstadoCiviles")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<ExperienciaLaboral>("ExperienciaLaborales")
             .EntityType
             .Filter()
             .Count()
             .Expand(10)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<Funcionario>("Funcionarios")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<FuncionarioCentroCosto>("FuncionarioCentroCostos")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<FuncionNomina>("FuncionNominas")
             .EntityType
             .Filter()
             .Count()
             .Expand(30)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<Sexo>("Sexos")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<GastoViaje>("GastoViajes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Grupo>("Grupos")
            .EntityType
            .Filter()
            .Count()
            .Expand(50)
            .OrderBy()
            .Page()
            .Select();
            builder.EntitySet<GrupoNomina>("GrupoNominas")
             .EntityType
             .Filter()
             .Count()
             .Expand(10)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<HoraExtra>("HoraExtras")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<HojaDeVida>("HojaDeVidas")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<HojaDeVidaDocumento>("HojaDeVidaDocumentos")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<HojaDeVidaEstudio>("HojaDeVidaEstudios")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<HojaDeVidaExperienciaLaboral>("HojaDeVidaExperienciaLaborales")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<InformacionFamiliar>("InformacionFamiliares")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<Idioma>("Idiomas")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<JornadaLaboral>("JornadaLaborales")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<JornadaLaboralDia>("JornadaLaboralDias")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NivelCargo>("NivelCargos")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NivelEducativo>("NivelEducativos")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<MotivoVacante>("MotivoVacantes")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NaturalezaJuridica>("NaturalezaJuridicas")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<Nomina>("Nominas")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NominaContabilidad>("NominaContabilidades")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NominaCentroCosto>("NominaCentroCostos")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NominaDetalle>("NominaDetalles")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NominaFuenteNovedad>("NominaFuenteNovedades")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NominaFuncionario>("NominaFuncionarios")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<Notificacion>("Notificaciones")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NotificacionDestinatario>("NotificacionDestinatarios")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<NotificacionDestinatarioLog>("NotificacionDestinatarioLogs")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<LicenciaConduccion>("LicenciaConducciones")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<Libranza>("Libranzas")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<LibranzaSubperiodo>("LibranzaSubperiodos")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<LibroVacacion>("LibroVacaciones")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<_LogConfiguracion>("LogConfiguraciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Novedad>("Novedades")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<NovedadSubperiodo>("NovedadSubperiodos")
             .EntityType
             .Filter()
             .Count()
             .Expand(50)
             .OrderBy()
             .Page()
             .Select();
            builder.EntitySet<Ocupacion>("Ocupaciones")
              .EntityType
              .Filter()
              .Count()
              .Expand(50)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<ContratoOtroSi>("ContratoOtroSis")
              .EntityType
              .Filter()
              .Count()
              .Expand(30)
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<Pais>("Paises")
                .EntityType
                .Filter()
                .Count()
                .Expand(30)
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<ParametroGeneral>("ParametroGenerales")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Parentesco>("Parentescos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<PeriodoContable>("PeriodoContables")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Profesion>("Profesiones")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ProrrogaAusentismo>("ProrrogaAusentismos")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<RangoUvt>("RangoUvts")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAusentismo>("TipoAusentismos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoCuenta>("TipoCuentas")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoContrato>("TipoContratos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoDocumento>("TipoDocumentos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoGastoViaje>("TipoGastoViajes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoMoneda>("TipoMonedas")
                .EntityType
                .Filter()
                .Count()
                .Expand(10)
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<TipoPeriodo>("TipoPeriodos")
                .EntityType
                .Filter()
                .Count()
                .Expand(10)
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<TipoSangre>("TipoSangres")
                .EntityType
                .Filter()
                .Count()
                .Expand(50)
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<TipoSoporte>("TipoSoportes")
                .EntityType
                .Filter()
                .Count()
                .Expand()
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<TipoVivienda>("TipoViviendas")
                .EntityType
                .Filter()
                .Count()
                .Expand(50)
                .OrderBy()
                .Page()
                .Select();
            builder.EntitySet<InformacionBasica>("InformacionBasicas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Administradora>("Administradoras")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ActividadEconomica>("ActividadEconomicas")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<DivisionPoliticaNivel1>("DivisionPoliticaNiveles1")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<DivisionPoliticaNivel2>("DivisionPoliticaNiveles2")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<OperadorPago>("OperadorPagos")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoContribuyente>("TipoContribuyentes")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<FormaPago>("FormaPagos")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<DiagnosticoCie>("DiagnosticoCies")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<TipoAdministradora>("TipoAdministradoras")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<EntidadFinanciera>("EntidadFinancieras")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Juzgado>("Juzgados")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<MotivoSolicitudCesantia>("MotivoSolicitudCesantias")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<NomenclaturaDian>("NomenclaturaDians")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Dependencia>("Dependencias")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<DependenciaJerarquia>("DependenciaJerarquias")
              .EntityType
              .Filter()
              .Count()
              .Expand()
              .OrderBy()
              .Page()
              .Select();
            builder.EntitySet<FuncionarioEstudio>("FuncionarioEstudios")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Calendario>("Calendarios")
               .EntityType
               .Filter()
               .Count()
               .Expand()
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<RequisicionPersonal>("RequisicionPersonales")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SolicitudCesantia>("SolicitudCesantias")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SolicitudPermiso>("SolicitudPermisos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SolicitudVacacion>("SolicitudVacaciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SolicitudVacacionesInterrupcion>("SolicitudVacacionesInterrupciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SoporteSolicitudPermiso>("SoporteSolicitudPermisos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SubPeriodo>("SubPeriodos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Sustituto>("Sustitutos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoLiquidacion>("TipoLiquidaciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoLiquidacionConcepto>("TipoLiquidacionConceptos")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoLiquidacionEstado>("TipoLiquidacionEstados")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoLiquidacionModulo>("TipoLiquidacionModulos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<RepresentanteEmpresa>("RepresentanteEmpresas")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<VariableNomina>("VariableNominas")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<FuncionVariable>("FuncionVariables")
               .EntityType
               .Filter()
               .Count()
               .Expand(10)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoCotizanteTipoPlanilla>("TipoCotizanteTipoPlanillas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoEmbargo>("TipoEmbargos")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoEmbargoConceptoNomina>("TipoEmbargoConceptoNominas")
               .EntityType
               .Filter()
               .Count()
               .Expand(30)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<FuncionarioDatoActual>("FuncionarioDatoActuales")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<Tercero>("Terceros")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAccion>("TipoAcciones")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoBeneficio>("TipoBeneficios")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoHoraExtra>("TipoHoraExtras")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoBeneficioRequisito>("TipoBeneficioRequisitos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TareaProgramada>("TareaProgramadas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TareaProgramadaLog>("TareaProgramadaLogs")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<VistaNominaFuncionario>("VistaNominaFuncionarios")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();


            builder.EntitySet<TipoPersona>("TipoPersonas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoPlanilla>("TipoPlanillas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoCotizante>("TipoCotizantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAportante>("TipoAportantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ClaseAportante>("ClaseAportantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<SubtipoCotizante>("SubtipoCotizantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoCotizanteSubtipoCotizante>("TipoCotizanteSubtipoCotizantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAportanteTipoPlanilla>("TipoAportanteTipoPlanillas")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoAportanteTipoCotizante>("TipoAportanteTipoCotizantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<TipoLiquidacionComprobante>("TipoLiquidacionComprobantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<ClaseAportanteTipoCotizante>("ClaseAportanteTipoCotizantes")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<_EnlaceExterno>("_EnlaceExternos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();
            builder.EntitySet<_MenuFavorito>("_MenuFavoritos")
               .EntityType
               .Filter()
               .Count()
               .Expand(50)
               .OrderBy()
               .Page()
               .Select();

            #region Custom 

            builder.Function("GetNominaFuncionarioDatoActuales")
                .Returns<IQueryable<VistaNominaFuncionario>>()
                .Parameter<int>("NominaId");


            var vistaNominaValor = builder.Function("GetNominaValorTotal").Returns<IQueryable<VistaNominaValor>>();
            vistaNominaValor.Parameter<DateTime>("FechaInicial").Required();
            vistaNominaValor.Parameter<DateTime>("FechaFinal").Required();
            #endregion

            return builder.GetEdmModel();
        }
    }
}

