SELECT
NULL AS Adjunto, 
(CASE WHEN RTRIM(TELEFONO1) = '' THEN '0' ELSE TELEFONO1 END) AS Celular,
NULL AS ClaseLibretaMilitarId,
E_MAIL AS CorreoElectronicoCorporativo,
U_EMAIL_ALTERNO AS CorreoElectronicoPersonal,
'sistema' AS CreadoPor,
1 AS DigitoVerificacion,
DIRECCION_HAB AS Direccion,
NULL AS Distrito,
NULL AS DivisionPoliticaNivel2ExpedicionDocumentoId,
NULL AS DivisionPoliticaNivel2OrigenId,
UBICACION AS DivisionPoliticaNivel2ResidenciaId,
NULL AS EliminadoPor,
(CASE ESTADO_EMPLEADO WHEN 'INAC' THEN 'Retirado' WHEN 'ACT' THEN 'Seleccionado' ELSE 'Retirado' END) AS Estado,
(CASE ESTADO_CIVIL WHEN 'U' THEN 5 WHEN 'C' THEN 1 WHEN 'D' THEN 2 WHEN 'O' THEN 7 WHEN 'V' THEN 6 WHEN 'S' THEN 3 ELSE 7 END) AS EstadoCivilId,
(CASE ACTIVO WHEN 'N' THEN 'Inactivo' WHEN 'S' THEN 'Activo' ELSE 'Inactivo' END) AS EstadoRegistro,
CreateDate AS FechaCreacion,
NULL AS FechaEliminacion,
DATEADD(year, 18, FECHA_NACIMIENTO) AS FechaExpedicionDocumento,
NULL AS FechaModificacion,
FECHA_NACIMIENTO AS FechaNacimiento,
NULL AS LicenciaConduccionAFechaVencimiento,
NULL AS LicenciaConduccionAId,
NULL AS LicenciaConduccionBFechaVencimiento,
NULL AS LicenciaConduccionBId,
NULL AS LicenciaConduccionCFechaVencimiento,
NULL AS LicenciaConduccionCId,
NULL AS ModificadoPor,
IDENTIFICACION AS Nit,
RUBRO3 AS NumeroCalzado,
IDENTIFICACION AS NumeroDocumento,
NULL AS NumeroLibreta,
493 AS OcupacionId,
0 AS Pensionado,
RUBRO8 AS PrimerApellido,
RUBRO6 AS PrimerNombre,
RUBRO9 AS SegundoApellido,
RUBRO7 AS SegundoNombre,
(CASE SEXO  WHEN 'F' THEN 1 WHEN 'M' THEN 2 ELSE 2 END) AS SexoId,
RUBRO1 AS TallaCamisa,
RUBRO2 AS TallaPantalon,
(CASE WHEN RTRIM(TELEFONO2) = '' THEN '0' ELSE TELEFONO2 END) AS TelefonoFijo,
(CASE WHEN floor((cast(convert(varchar(8),getdate(),112) as int)-cast(convert(varchar(8),FECHA_NACIMIENTO,112) as int) ) / 10000) > 18 THEN 3 ELSE 2 END) AS TipoDocumentoId,
(CASE TIPO_SANGRE WHEN 'O-' THEN 6 WHEN 'A+' THEN 1 WHEN 'A-' THEN 2 WHEN 'B-' THEN 8 WHEN 'O+' THEN 5 WHEN 'AB-' THEN 4 WHEN 'B+' THEN 7 WHEN 'AB+' THEN 3 WHEN 'ND' THEN 5 ELSE 5 END) AS TipoSangreId,
3 AS TipoViviendaId,
0 AS UsaLentes
FROM alcanos.alcanos.EMPLEADO



 