SET IDENTITY_INSERT [dbo].[Dependencia] ON 
GO
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(1,'S-P-GTEGRA','Gerencia general','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(2,'S-DGH-RL','Dirección de gestión humana','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(3,'NC-PY-REVP','Dirección de calidad de obra','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(4,'NG-DR-REPY','Dirección técnica','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(5,'NG-DR-SEVT','Dirección de servicios técnicos','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(6,'S-DA-COMPR','Dirección de abastecimiento','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(7,'NG-DR-COM','Dirección comercial','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(8,'S-P-DIRJUR','Dirección jurídica','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(9,'S-DA-ADFIN','Dirección administrativa y financiera','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(10,'S-P-SISTEM','Tecnologias de la información y las comunicaciones (TIC)','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(11,'S-P-CONTIN','Control interno','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(12,'S-P-AUDITO','Auditoria','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(13,'S-P-GCIACO','Gerencia CO','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(14,'NG-DI-INSC','Organismo técnico de inspección y certificación','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(15,'NG-DI-INTE','Interventoria','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(16,'NG-DR-METR','Metrología y estándares','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(17,'S-DGH-RL','Relaciones laborales','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(18,'S-P-HSEQ','HSEQ','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(19,'S-DGH-GH','Gestión humana','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(20,'S-DGH-GH','Bienestar laboral','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(21,'S-DGH-GH','Capacitación y desarrollo','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(22,'NG-DR-CART','Cartografia','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(23,'O-DR-O&M','Operación y mantenimiento','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(24,'NG-DR-REDE','Redes','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(25,'O-DR-GNC','Gas natural comprimido','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(26,'PROY-ING','Proyectos e ingenieria','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(27,'CTRL-OPER','Central de operaciones','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(28,'S-DO-SERAS','Servicios asociados','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(29,'NC-PY-INST','Construcciones','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(30,'S-P-CONPER','Control pérdidas','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(31,'S-DA-COMPR','Compras y contratación','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(32,'S-DA-ADCT','Gestión de almacenes e inventarios','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(33,'O-DCG-COMG','Comercialización de gas','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(34,'S-P-CALLCE','Contact center','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(35,'O-DA-FACTU','Facturación','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(36,'O-DA-SEVCL','Servicio al cliente','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(37,'NC-PY-INSV','Mercadeo y ventas','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(38,'S-DA-TESOR','Tesoreria','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(39,'S-P-PLANDE','Planeación y regulación','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(40,'S-DA-SEGEN','Servicios generales','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(41,'O-DA-CARTE','Cartera','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(42,'S-DA-SEGEN','Gestión documental','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(43,'S-DA-CONTA','Contabilidad e impuestos','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(44,'S-P-SISTEM','Hardware y redes','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(45,'S-P-SISTEM','Desarrollo y soporte','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(46,'S-P-SISTEM','Infraestructura','Activo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(47,'NC-PY-FACT','PROYECTO FACTURACION','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(48,'S-DGH-GHUM','DIRECCION GESTION HUMANA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(49,'NC-PY-INSA','PROY INSTALACION ACOMETIDAS-MDO. ABIERTO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(50,'NC-PY-SERV','PROYECTO SERVICIOS TECNICOS','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(51,'O-DR-MANT','MANTENIMIENTO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(52,'NC-PY-INCO','PROYECTO INSTALACIONES - CONSTRUCTORA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(53,'OTN-PY-CON','OTI NUEVAS PROYECTO CONSTRUCTORA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(54,'OTN-PY-MAB','OTI NUEVAS MERCADO ABIERTO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(55,'S-DGH-PYNO','PROYECTO NOMINA GH','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(56,'ND','No definido','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(57,'S-P-COMUNI','COMUNICACIÓN','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(58,'S-P-PRESID','PRESIDENCIA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(59,'S-P-SECRGR','SECRETARIA GENERAL','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(60,'NG-DC-CONS','DIRECCION DE CONSTRUCCIONES','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(61,'NG-DV-VENT','VENTAS','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(62,'S-P-COFUSA','CENTRO OPERATIVO FUSAGASUGA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(63,'S-P-COGIRA','CENTRO OPERATIVO GIRARDOT','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(64,'S-P-CODORA','CENTRO OPERATIVO LA DORADA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(65,'S-P-COIBAG','CENTRO OPERATIVO IBAGUE','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(66,'S-P-COFLOR','CENTRO OPERATIVO FLORENCIA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(67,'S-P-COPOPA','CENTRO OPERATIVO POPAYAN','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(68,'S-P-CORION','CENTRO OPERATIVO RIONEGRO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(69,'M-05-615-O','RIONEGRO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(70,'M-17-380-O','DORADA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(71,'M-18-001-O','FLORENCIA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(72,'M-19-001-O','POPAYAN','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(73,'M-25-307-O','GIRARDOT','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(74,'M-41-001-F','NEIVAFACTURACION','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(75,'M-41-001-H','NEIVAG/HUMANA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(76,'M-41-001-T','NEIVATECNICA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(77,'M-41-001-S','NEIVATESORERIA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(78,'M-73-001-O','IBAGUE','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(79,'S-P-JURID','JURIDICO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(80,'S-P-COPAST','CENTRO OPERATIVO PASTO','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(81,'O-DA-COFAC','COORDINACION FACTURACION','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(82,'METROGAS','METROGAS','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(83,'O-DR-OPER','OPERACIÓN','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(84,'NC-PY-IACO','PROY INSTALACION ACOMETIDAS-CONSTRUCTORA','Inactivo','sistema',GETDATE());
INSERT INTO dbo.Dependencia (Id,Codigo, Nombre, EstadoRegistro, CreadoPor, FechaCreacion) VALUES(85,'S-D-ABASTE','','Inactivo','sistema',GETDATE());

SET IDENTITY_INSERT [dbo].[Dependencia] OFF 
GO