INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(1,'JEFEINTE','Táctico 1','JEFE DE INTERVENTORIA','Nacional','Establecer los planes, políticas, procedimientos, controles a las obras civiles desarrolladas por los contratistas, tanto en 
redes, acometidas, internas y servicios.','Interventoria','DIRECTOR CALIDAD DE OBRA','')
,(2,'ANALOTI ','Táctico 2','ANALISTA OTI','Nacional','Contribuir brindando asistencia administrativa y operativa a la Dirección calidad de obra y certificación en lo concerniente a los procesos del Organismo Técnico de inspección. Analizar información y presentar informes que brinden el apoyo suficiente para toma de decisiones del Director Calidad de Obra y Certificación.','Organismo técnico de inspección y certificación','DIRECTOR CALIDAD DE OBRA','')
,(3,'AUDTCNII','Táctico 2','AUDITOR TECNICO CONTROL INTERNO II','CentroOperativo','Revisar, asesorar y promover la implementación y funcionamiento del Sistema de Control Interno en los procesos, recomendando las acciones de mejoramiento continuo, para el logro de la misión y objetivos institucionales, con eficiencia, eficacia y efectividad.','Control interno','JEFE DE CONTROL INTERNO','')
,(4,'DIRCALOB','Estratégico','DIRECTOR CALIDAD DE OBRA','Nacional','Asegurar la conformidad en la inspección de instalaciones nuevas, modificadas, y en servicio, y dar un correcto direccionamiento a los procesos de certificación de instalaciones nuevas, revisiones periódicas, interventoría, metrología y estándares con el fin de garantizar la seguridad de las mismas.','Dirección de calidad de obra','GERENTE GENERAL','')
,(5,'DIRCIAL','Estratégico','DIRECTOR COMERCIAL','Nacional','Dirigir los procesos comerciales con un enfoque innovador que genere oportunidades de negocio, diseñando estrategias comerciales para lograr posicionamiento, resultados que aseguran rentabilidad y el crecimiento económico sostenible para la organización.','Dirección comercial','GERENTE GENERAL','')
,(6,'DIRJURID','Estratégico','DIRECTOR JURIDICO','Nacional','Participar y asesorar de forma eficiente y oportuna en todos los temas legales y/o jurídicos con el fin de garantizar la viabilidad, protección y defensa legal de los derechos e intereses de ALCANOS DE COLOMBIA S.A. E.S.P, asegurando la
correcta aplicación de las leyes, reglamentos y disposiciones legales vigentes.','Dirección jurídica','GERENTE GENERAL','')
,(7,'DIRSERTE','Estratégico','DIRECTOR SERVICIOS TECNICOS','Nacional','Establecer la estrategia de desarrollo operacional satisfaciendo las expectativas de los clientes, garantizando la viabilidad y sostenibilidad de los procesos de la Dirección de Servicios Técnicos.','Dirección de servicios técnicos','GERENTE GENERAL','')
,(8,'DIRTECNI','Estratégico','DIRECTOR TECNICO','Nacional','Garantizar la continuidad del servicio y atender de manera oportuna, segura y rentable las demandas de gas natural en las zonas de influencia y nuevos mercados de la compañía.','Dirección técnica','GERENTE GENERAL','')
,(9,'JEFECINT','Estratégico','JEFE DE CONTROL INTERNO','Nacional','Efectuar el direccionamiento, retroalimentación y asesoramiento en el diseño y puesta en marcha de los procesos de gestión que desarrolla la compañía, para el logro de los objetivos administrativos salvaguardando los activos y velando por el bienestar integral de un correcto funcionamiento, evaluación y efectividad del sistema de control interno pro-activo que cumpla con las políticas y directrices trazadas.','Control interno','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(10,'JEFESIST','Estratégico','JEFE DE SISTEMAS','Nacional','Garantizar la eficiencia y eficacia de la infraestructura tecnológica de sistemas dentro de la compañía, permitiendo que esté acorde a las necesidades existentes y de crecimiento de la empresa.','Tecnologias de la información y las comunicaciones (TIC)','GERENTE GENERAL','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(11,'JEFEJURI','Estratégico','JEFE JURIDICA','Nacional','Garantizar que se ejerza la defensa judicial y extrajudicial de los intereses de la compañía en el marco de los términos de ley y en cumplimiento de la normatividad vigente.','Dirección jurídica','GERENTE GENERAL','')
,(12,'ASISCONT','Operativo','ASISTENTE CONTABLE','Nacional','Dar apoyo en las actividades contables, financieras y tributarias de la Compañía, aportando en los procesos de registro, clasificación y contabilización de las transacciones.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(13,'ASIDIRTE','Operativo','ASISTENTE DE DIRECCION TECNICA','Nacional','Ejecutar, atender y asistir actividades que tengan relación con el área técnica para garantizar el cumplimiento de estas. Cumplir con las tareas asignadas para el cumplimiento de los procesos establecidos en la compañía.','Dirección técnica','DIRECTOR TECNICO','')
,(14,'ASIADMFR','Operativo','ASISTENTE DIRECCION ADTVA Y FINANCIERA','Nacional','Ejecutar, coordinar, atender y asistir actividades que tenga relación con el área administrativa y financiera para garantizar el cumplimiento de estas.','Dirección administrativa y financiera','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(15,'AUXADMCP','Operativo','AUXILIAR ADMINISTRATIVO CONTROL PERDIDAS','Nacional','Colaborar con las actividades del área de control de pérdidas de gas que permitan un buen desarrollo en los procesos administrativo de acuerdo con las instrucciones y directrices encomendadas.','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(16,'AUXADSAS','Operativo','AUXILIAR ADMINISTRATIVO SERVICIOS ASOCIA','CentroOperativo','Dar apoyo a las actividades del área de Servicios Asociados que permitan un buen desarrollo en los procesos administrativo de acuerdo con las instrucciones y directrices encomendadas','Servicios asociados','COORDINADOR SERVICIOS ASOCIADOS','GERENTE DE CentroOperativo')
,(17,'AUXCONII','Operativo','AUXILIAR CONTABLE II','Nacional','Revisar, clasificar, codificar, organizar, controlar, elaborar, entregar, liquidar, verificar y registrar sistemáticamente en forma ordenada y oportuna todos los hechos económicos de la compañía de acuerdo con los procesos, procedimientos y políticas establecidas, las directrices del jefe inmediato y conforme a las disposiciones contables, fiscales y legales que se apliquen a cada situación.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(18,'AUXIACOM','Operativo','AUXILIAR DE ACOMETIDAS','CentroOperativo','Garantizar la productividad de las cuadrillas de acometidas, asegurar la calidad de obra y mantener comunicación permanente con el coordinador de construcciones.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(19,'AUXIARCH','Operativo','AUXILIAR DE ARCHIVO','Nacional','Recibir toda la documentación interna y externa y dirigirla de manera óptima a todos los destinatarios teniendo en cuenta el procedimiento establecido para la administración de documentos','Gestión documental','ADMINISTRADOR DE ARCHIVO','')
,(20,'AUXAMPO','Operativo','AUXILIAR DE CAMPO','CentroOperativo','Dar soporte operativo a facturación en los procedimientos asociados con toma de lecturas, entrega de facturas y otras afines','Facturación','SUPERVISOR CAMPO','JEFE DE FACTURACION')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(21,'AUXCARTO','Operativo','AUXILIAR DE CARTOGRAFIA','Nacional','Ejecutar actividades operativas para la construcción, actualización y mantenimiento de la base de cartografía de la compañía, teniendo como marco las normas y estándares establecidos.','Cartografia','JEFE DE CARTOGRAFIA','')
,(22,'AUXICOMG','Operativo','AUXILIAR DE COMERCIALIZACION DE GAS','Nacional','Gestionar operativamente, las contrataciones y nominaciones de compras y/o las ventas a Grandes Clientes (Industrias y GNCV), de suministro y/o transporte de gas natural; logrando oportuno cumplimiento comercial y regulatorio de sus variables críticas. Aportar a la Jefatura de Comercialización de gas con mejoramiento de los procesos y el equipo de trabajo','Comercialización de gas','JEFE COMERCIALIZACION DE GAS','')
,(23,'AUXCOMIN','Operativo','AUXILIAR DE COMUNICACIONES INTERNAS','Nacional','Realizar el apoyo en el diseño, elaboración y comunicación de material gráfico, audiovisual y apoyo logístico general de las actividades y programas propios del área de Bienestar y comunicaciones internas, generando alternativas de mejora en canales de comunicación para la satisfacción y calidad de vida de los colaboradores.','Bienestar laboral','PROFESIONAL DE BIENESTAR LABORAL','')
,(24,'AUXIFACT','Operativo','AUXILIAR DE FACTURACION I','CentroOperativo','Gestionar y ejecutar el proceso de facturación en actividades de liquidación, toma de lecturas, impresión, entrega de facturas, PQR´S, entre otros.','Facturación','JEFE DE FACTURACION','')
,(25,'AUXFACT2','Operativo','AUXILIAR DE FACTURACION II','CentroOperativo','Realizar la planificación, gestión y seguimiento de los procedimientos y actividades establecidas en facturación para lograr el cumplimiento de los cronogramas e indicadores que dan alcance a los objetivos del área en beneficio de la organización.','Facturación','JEFE DE FACTURACION','')
,(26,'AUXIGEHU','Operativo','AUXILIAR DE GESTION HUMANA','Nacional','Dar apoyo a la Coordinación de Relaciones Laborales y al Administrador de Nómina en las diferentes actividades que propenden por la administración de los procesos establecidos en la misma en el área de Gestión Humana.','Relaciones laborales','COORDINADOR DE RELACIONES LABORALES','')
,(27,'AUXINFRA','Operativo','AUXILIAR DE INFRAESTRUCTURA','Nacional','Ejecutar las tareas operativas relacionadas con la administración de servidores, bases de datos y equipos de seguridad de la Compañía, garantizando su disponibilidad, desempeño, integridad, seguridad y recuperabilidad oportuna.','Infraestructura','ADMINISTRADOR DEL SISTEMA','')
,(28,'AUXINOMI','Operativo','AUXILIAR DE NOMINA','Nacional','Dar apoyo en el manejo del programa de nómina y demás procesos de gestión humana, bajo las políticas establecidas por la compañía y la normatividad laboral, generando confiabilidad y veracidad en la información.','Relaciones laborales','ADMINISTRADOR DE NOMINA I','')
,(29,'AUXSERCL','Operativo','AUXILIAR DE SERVICIO AL CLIENTE','CentroOperativo','Recibir el pago de los abonos a factura y recibos de caja a los clientes que se acerquen a cancelar a las oficinas y recepcionar todas las solicitudes de los usuarios (PQR) y registrarlas en el sistema dando un trato cordial a los clientes buscando solución efectiva de las mismas.','Servicio al cliente','GERENTE DE CentroOperativo','')
,(30,'AUXISIST','Operativo','AUXILIAR DE SISTEMAS','Nacional','Dar soporte a nivel de hardware y software a los usuarios y velar por la actualización oportuna de esta plataforma.','Hardware y redes','COORDINADOR DE HARDWARE Y REDES','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(31,'AUXTESOR','Operativo','AUXILIAR DE TESORERIA','Nacional','Realizar actividades de manejo de recaudos tercerizados y pagos a proveedores.','Tesoreria','JEFE DE TESORERIA','')
,(32,'AUXIJURI','Operativo','AUXILIAR JURIDICO','Nacional','Recibir, resguardar, gestionar y dar seguimiento a los documentos que allegan a Jurídica, ejecutando actividades de reporte de información, archivo y custodia de documentos, en una unidad de archivo física y magnética a fin de mantener la información actualizada y organizada en el Listado Maestro de Correspondencia, a disposición de la empresa, de manera que permita analizarla de acuerdo a las necesidades para dar respuesta oportuna y proveyendo la información que se requiera para el proceso de toma de decisiones, guardando confidencialidad respecto de la misma.','Dirección jurídica','DIRECTOR JURIDICO','')
,(33,'AUXSOPTE','Operativo','AUXILIAR SOPORTE TECNICO','Nacional','Realizar el seguimiento y control de facturación del área técnica, encaminada al cumplimiento estricto de los manuales y procedimientos establecidos para cada una de las subáreas (Construcción de redes, instalaciones, servicios de presupuestos y O&M) en los diferentes centros operativos de la compañía.','Redes','JEFE DE REDES','')
,(34,'AUXTEADT','Operativo','AUXILIAR TECNICO ADMINISTRATIVO','CentroOperativo','Dar soporte a todos los procesos administrativos y operativos delegados por su Jefe inmediato.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(35,'AUXTECCN','Operativo','AUXILIAR TECNICO DE CONSTRUCCIONES','CentroOperativo','Garantizar y supervisar la calidad de obra de los contratistas e instaladores de la compañía y manteniendo los niveles de servicio establecidos.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(36,'AUXTEO&M','Operativo','AUXILIAR TECNICO DE O Y M','CentroOperativo','Realizar las funciones técnico-operativas que requieren los sistemas de distribución para que operen de forma segura y continua. A su vez, realizar suspensiones y/o reconexiones del servicio cada vez que sea necesario.','Operación y mantenimiento','COORDINADOR DE O Y M','GERENTE DE CentroOperativo')
,(37,'AUXTETEL','Operativo','AUXILIAR TECNICO DE TELEMETRIA','Nacional','Colaborar en actividades operativas de tele medición. Estará en constante comunicación con el Analista de Telemetría, Líder de mantenimiento y auxiliares técnicos de operación y mantenimiento con miras a garantizar el funcionamiento óptimo del sistema de telemetría de la compañía.','Central de operaciones','COORDINADOR CENTRAL OPERACIONES','')
,(38,'AUXTECSA','Operativo','AUXILIAR TECNICO SERVICIOS ASOCIADOS','CentroOperativo','Atender las solicitudes de servicio internas y externas de la compañía, de tal manera que permitan garantizar la operación de los sistemas de distribución, Identificar durante visitas en campo posibles anomalías, atender las novedades de las instalaciones y/o requerimientos de asesorías técnicas de los usuarios.','Servicios asociados','SUPERVISOR SERVICIOS ASOCIADOS','GERENTE DE CentroOperativo')
,(39,'AUXTECPO','Operativo','AUXILIAR TECNICO SERVICIOS POPAYAN','CentroOperativo','Realizar la supervisión y garantizar la calidad de obra de los contratistas e instaladores de la compañía y mantener los niveles de servicio establecidos.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(40,'AYUDOBRG','Operativo','AYUDANTE OBRA GIRARDOT','CentroOperativo','Garantizar la ubicación del centro de medición cumpliendo con la normatividad y los procedimientos establecidos','Construcciones','COORDINADOR DE CONSTRUCCIONES','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(41,'CONDGRAL','Operativo','CONDUCTOR GERENCIA GENERAL','Nacional','Conducir el vehículo asignado con el objetivo de apoyar la gestión del CentroOperativo al que pertenecen. Dicha conducción debe realizarse responsablemente y respetando las normas de tránsito existentes.','Gerencia CO','GERENTE GENERAL','')
,(42,'CONDUCTO','Operativo','CONDUCTOR','CentroOperativo','Conducir el vehículo asignado, apoyando la gestión del CentroOperativo al que pertenecen. Dicha conducción debe realizarse responsablemente y respetando las normas de tránsito existentes.','Gerencia CO','GERENTE GENERAL','')
,(43,'DELINEAN','Operativo','DELINEANTE','Nacional','Ejecutar la actualización y mantenimiento de la base cartográfica de la compañía, mediante la digitalización de la información predial y de redes reportada al área','Cartografia','JEFE DE CARTOGRAFIA','')
,(44,'DIGIOTI','Operativo','DIGITADOR OTI','CentroOperativo','Realizar la digitación de toda la información relacionada al proceso de inspección de instalaciones de gas natural y control de la digitación de actas, certificados de conformidad y novedades del OTI.','Organismo técnico de inspección y certificación','COORDINADOR OTI','GERENTE DE CentroOperativo')
,(45,'EJECCIAL','Operativo','EJECUTIVO COMERCIAL','Nacional','Dar apoyo y seguimiento a los proyectos constructoras y clientes comerciales de la compañía, ayudando al control de la cartera e incremento del consumo de gas y prestación del servicio','Mercadeo y ventas','JEFE DE VENTAS','')
,(46,'GESTADTI','Operativo','GESTOR ADMINISTRATIVO TI','Nacional','Soportar la gestión administrativa y operacional de los servicios de Tecnología de la Información, con el fin de dar cumplimiento a los niveles de servicio acordados con los clientes.','Hardware y redes','COORDINADOR DE HARDWARE Y REDES','')
,(47,'GESCARTE','Operativo','GESTOR DE CARTERA','CentroOperativo','Realizar la respectiva persuasión del usuario hacia el pago de la obligación en mora correspondiente al servicio de gas natural; ofreciendo información exacta sobre estado de cuenta, políticas, financiación y opciones y modalidades de pago ofrecidas por la organización y cumpliendo cabalmente con los parámetros fijadas por esta.','Cartera','COORDINADOR DE CARTERA','')
,(49,'GESTSOCI','Operativo','GESTOR SOCIAL','CentroOperativo','Realizar la socialización y sensibilización del Proyecto de Alcanos de Colombia S.A. E.S.P ante las comunidades donde se desarrolle, contribuyendo con el posicionamiento de la empresa.','Redes','COORDINADOR DE REDES','GERENTE DE CentroOperativo')
,(50,'INSPOTI','Operativo','INSPECTOR OTI','CentroOperativo','Realizar el proceso de inspección y certificación de instalaciones nuevas, modificadas y en servicio y todo lo referente con las revisiones periódicas de instalaciones para el suministro de gas en usuarios residenciales y comerciales. Así como dar cumplimiento con los objetivos de inspección de conformidad con los requerimientos de la compañía, asegurando un alto grado de confiabilidad y cumplimiento de la normatividad aplicable','Organismo técnico de inspección y certificación','COORDINADOR OTI','GERENTE DE CentroOperativo')
,(51,'INTALADO','Operativo','INSTALADOR','CentroOperativo','Realizar la construcción Técnica de Redes Internas de gas, garantizando y a satisfacción del usuario.','Construcciones','COORDINADOR DE CONSTRUCCIONES','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(52,'MENSAJER','Operativo','MENSAJERO','CentroOperativo','Realizar las actividades de mensajería interna y externa de forma eficiente y eficaz.','Tesoreria','JEFE DE TESORERIA','GERENTE DE CentroOperativo')
,(53,'PEGADC','Operativo','PEGADOR I','CentroOperativo','Garantizar seguridad y eficiencia en los sistemas operativos de los gasoductos, que conlleve a una excelente prestación del servicio y a la continuidad de este.','CONSTRUCCIONES','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(54,'PLANMTO','Operativo','PLANEADOR DE MANTENIMIENTO','Nacional','Elaborar los planes y la programación de mantenimiento de los activos de distribución de ALCANOS DE COLOMBIA S.A. E.S.P., buscando aumentar su eficiencia, minimizando los costos de mantenimiento, además de satisfacer las necesidades de los usuarios, en donde la responsabilidad no recae solo en el departamento de mantenimiento sino en toda la estructura de la empresa.','Operación y mantenimiento','LIDER DE MANTENIMIENTO','')
,(55,'SECRETAR','Operativo','SECRETARIA','Nacional','Ejecutar, coordinar, atender y asistir actividades que tenga relación con el área administrativa y financiera para garantizar el cumplimiento de las mismas.','Gerencia general','GERENTE GENERAL','')
,(56,'SUPERNCO','Operativo','SUPERNUMERARIO DE CO','CentroOperativo','Realizar los reemplazos a los cargos de Auxiliar de Servicio al Cliente, Auxiliar de Ventas, Recepcionista, Digitador de PQRs y demás tareas o actividades programadas por el Gerentes de los Centros Operativos','Gerencia CO','GERENTE DE CentroOperativo','')
,(57,'SUPCONCE','Operativo','SUPERVISOR CONTAC CENTER','Nacional','Garantizar que los planes, políticas, procedimientos y controles establecidos por la Coordinación del Contact Center se cumplan, con el fin de optimizar la eficiencia, oportunidad y excelencia de la atención de nuestros usuarios y clientes internos y externos.','Contact center','COORDINADOR CONTAC CENTER','')
,(58,'SUPCTRPE','Operativo','SUPERVISOR CONTROL PERDIDAS','CentroOperativo','Realizar la identificación, mediante la consulta de consumos e históricos de usuarios en el módulo de SICOM y en campo, las causas de pérdidas de gas natural mediante seguimiento al estado y funcionamiento de los equipos de medición, redes y acometidas, realizando acompañamiento permanente del personal a cargo y de las áreas a fines.','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(59,'SUPVMUNI','Operativo','SUPERVISOR DE MUNICIPIO','CentroOperativo','Recibir las peticiones, quejas y reclamos generados por usuarios; velar por la continuidad del servicio y el correcto funcionamiento de las redes y activos de distribución que se tengan a cargo y atender las emergencias generadas cumpliendo normatividad vigente.','Operación y mantenimiento','COORDINADOR DE O Y M','')
,(60,'SUPVREDE','Operativo','SUPERVISOR DE REDES','CentroOperativo','Realizar la supervisión y garantizar la calidad de obra de los contratistas y personal interno en la ejecución de nuevos proyectos u obras de ampliación - prolongación de redes de distribución en acero o polietileno.','Redes','COORDINADOR DE REDES','GERENTE DE CentroOperativo')
,(61,'SUPSERV','Operativo','SUPERVISOR SERVICIOS ASOCIADOS','CentroOperativo','Gestionar, administrar y realizar seguimiento en campo relacionado con la ejecución de las actividades diarias asignadas al contratista y o personal técnico, mediante los procedimientos establecidos y garantizando la calidad del servicio prestado','Servicios asociados','COORDINADOR SERVICIOS ASOCIADOS','GERENTE DE CentroOperativo')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(62,'TECARTOG','Operativo','TECNICO DE CARTOGRAFIA','Nacional','Ejecutar actividades operativas para atender las demandas internas y externas, que se traduce en la generación, actualización y mantenimiento de cartografía en todos los niveles temáticos los cuales apunta a los diversos procesos y objetivos del área.','Cartografia','JEFE DE CARTOGRAFIA','')
,(63,'TECSOPOR','Operativo','TECNICO DE SOPORTE','Nacional','Dar apoyo integral a las áreas de negocio de la Compañía en el funcionamiento de los Sistemas de Información, con el fin de asegurar su correcta operatividad.','Desarrollo y soporte','COORDINADOR DESARROLLO Y SOPORTE','')
,(64,'APSEPROD','Operativo','APRENDIZ SENA ESTAPA PRODUCTIVA','CentroOperativo','Dar apoyo en el área la cual sea asignada para realizar su etapa practica','Gestión humana','COORDINADOR GESTION HUMANA','')
,(65,'TECHSEQ','Operativo','TECNOLOGO HSEQ','CentroOperativo','Realizar el control del cumplimiento y la eficacia del Sistema de Gestión de la Seguridad y Salud en el Trabajo.','HSEQ','JEFE DE HSEQ','')
,(66,'PROGCUAD','Operativo','PROGRAMADOR DE CUADRILLA','CentroOperativo','Realizar los planes de trabajo de las cuadrillas de Operación y Mantenimiento para garantizar la ejecución de órdenes de trabajo que garanticen la continuidad del servicio y la ejecución del plan de mantenimiento.','Operación y mantenimiento','COORDINADOR DE O Y M','')
,(67,'SUPCONST','Operativo','SUPERVISOR DE CONSTRUCCIONES','CentroOperativo','Gestionar y desarrollar las actividades que permitan garantizar el adecuado desempeño y productividad de las cuadrillas a su cargo, asegurando la calidad de la obra ejecutada y manteniendo un canal de comunicación y reporte permanente con el Coordinador de Construcciones; así como también un trato amable y fluido con los usuarios.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(68,'COORCONC','Táctico 1','COORDINADOR CONTAC CENTER','Nacional','Coordinar y controlar el Contact Center de Alcanos de Colombia S.A E.S.P, de tal forma que responda a las estrategias comerciales de la Compañía y dar una excelente atención a las solicitudes recibidas por canal telefónico, dando cumplimiento de las normas y parámetros establecidos. Además tiene a cargo el equipo humano que conforma ésta área.','Contact center','JEFE SERVICIO AL CLIENTE','')
,(69,'COORCOIN','Táctico 1','COORDINADOR DE CONTROL DE INVENTARIOS','Nacional','Coordinar las actividades desarrolladas para el Control de los Inventarios de la compañía, garantizando su adecuado manejo y uso final.','Gestión de almacenes e inventarios','JEFE ADMINISTRACION ACTIVOS','')
,(70,'COORGNC','Táctico 1','COORDINADOR DE GNC','Nacional','Coordinar las actividades desarrolladas para el Control de los Inventarios de la compañía, garantizando su adecuado manejo y uso final.','Gas natural comprimido','JEFE DE GNC','')
,(71,'COORHARE','Táctico 1','COORDINADOR DE HARDWARE Y REDES','Nacional','Garantizar la disponibilidad, vigencia y documentación de la plataforma tecnológica de la Compañía en lo que respecta a hardware y redes.','Hardware y redes','JEFE DE SISTEMAS','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(72,'COORDO&M','Táctico 1','COORDINADOR DE O Y M','CentroOperativo','Coordinar y verificar el cumplimiento del cronograma de operaciones de los sistemas de distribución de gas natural que opera la empresa, para los gasoductos en el área de influencia, con el fin de brindar un servicio seguro, continuo y de calidad.','Operación y mantenimiento','GERENTE DE CentroOperativo','')
,(73,'COORPROY','Táctico 1','COORDINADOR DE PROYECTOS','Nacional','Coordinar los recursos asignados por la compañía para alcanzar los objetivos de los proyectos en calidad, costo y 
oportunidad, teniendo un excelente relacionamiento con clientes internos y externos.','Proyectos e ingenieria','JEFE DE PROYECTOS','')
,(74,'COORELAB','Táctico 1','COORDINADOR DE RELACIONES LABORALES','Nacional','Coordinar, garantizar y asegurar los procesos de contratación, nomina, administración de personal, relacionamiento y 
disciplina, desvinculación.','Relaciones laborales','DIRECTOR DE GESTION HUMANA','')
,(75,'COORVENT','Táctico 1','COORDINADOR DE VENTAS','CentroOperativo','Efectuar el cumplimiento del presupuesto de ventas de los municipios a cargo, logrando satisfacer con calidad y eficiencia las expectativas de los clientes, mediante el manejo adecuado de los recursos asignados.','Mercadeo y ventas','DIRECTOR COMERCIAL','')
,(76,'COORGESH','Táctico 1','COORDINADOR GESTION HUMANA','Nacional','Coordinar, controlar y asegurar los procesos de reclutamiento, selección, evaluación de desempeño, capacitación y desarrollo del personal de ALCANOS DE COLOMBIA E.S.P S.A a nivel Nacional.','Gestión humana','DIRECTOR DE GESTION HUMANA','')
,(77,'COOROTI','Táctico 1','COORDINADOR OTI','CentroOperativo','Coordinar, organizar, controlar y gestionar la ejecución de las actividades de inspección realizadas por el personal operativo y personal administrativo bajo su cargo del Organismo Técnico de Inspección, para dar cumplimiento a lo establecido en la NTC 17020 y resolución 90902 del 2013 y demás normas vigentes.','Organismo técnico de inspección y certificación','DIRECTOR CALIDAD DE OBRA','GERENTE DE CentroOperativo')
,(78,'COORSERA','Táctico 1','COORDINADOR SERVICIOS ASOCIADOS','CentroOperativo','Coordinar y administrar el seguimiento a la ejecución de las actividades establecidas, basadas en los requisitos normativos para la prestación de Servicios de Gas Natural para los clientes internos y externos de la Compañía, garantizando la satisfacción y respuesta en los tiempos establecidos.','Servicios asociados','GERENTE DE CentroOperativo','LIDER NACIONAL SERVICIOS ASOCIADOS')
,(79,'JEFADMAC','Táctico 1','JEFE ADMINISTRACION ACTIVOS','Nacional','Coordinar, supervisar y controlar los activos fijos e Inventario de la Compañía, con el fin de garantizar un adecuado manejo y uso final. Asimismo, proponer mejores prácticas empresariales, para una apropiada administración de los activos fijos e inventario y buscar el mejoramiento continuo del Proceso.','Gestión de almacenes e inventarios','DIRECTOR DE ABASTECIMIENTO','')
,(80,'JEFECART','Táctico 1','JEFE DE CARTERA','Nacional','Garantizar y gestionar el cobro de cartera a favor de la organización, administrando y controlando la cartera de clientes garantizando la adecuada y oportuna captación de recursos y así, obtener los mejores resultados en rentabilidad, volumen y crecimiento financiero de acuerdo con los parámetros y estándares de la organización.','Cartera','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(81,'JEFCOMPR','Táctico 1','JEFE DE COMPRAS','Nacional','Suministrar los materiales, suministros, bienes, servicios y equipos que requiera la compañía para su correcto funcionamiento.','Compras y contratación','DIRECTOR DE ABASTECIMIENTO','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(82,'JEFCONST','Táctico 1','JEFE DE CONSTRUCCIONES','Nacional','Coordinar todos los proyectos de obra y supervisar por la calidad de las construcciones y excelencia en el trabajo en términos de tiempo y calidad de los materiales.','Construcciones','DIRECTOR SERVICIOS TECNICOS','')
,(83,'JEFEPLAN','Táctico 1','JEFE DE PLANEACION','Nacional','Elaborar el cálculo de tarifas y la elaboración del presupuesto de la compañía.','Planeación y regulación','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(84,'JEFESERE','Táctico 1','JEFE DE SERVICIOS REGIONAL','Nacional','Garantizar la operatividad de todos los procesos del área técnica en la región a través de planes de trabajo que permitan cumplir con los objetivos organizacionales mediante los pilares de confianza, prontitud, calidad y seguridad que garanticen la satisfacción de los clientes y rentabilidad de los accionistas.','Gerencia CO','GERENTE DE CentroOperativo','')
,(85,'JEFEVENT','Táctico 1','JEFE DE VENTAS','Nacional','Coordinar, supervisar y velar por el cumplimiento de las metas teniendo en cuenta las estrategias comerciales para 
la consecución de las ventas que beneficien a la organización.','Mercadeo y ventas','DIRECTOR COMERCIAL','')
,(86,'JEFESEGR','Táctico 1','JEFE SERVICIOS GENERALES','Nacional','Garantizar el mantenimiento a la infraestructura y equipamiento de las entidades y dependencias, a través del cumplimiento de los programas anuales establecidos, así como atender las solicitudes de diversos servicios que presenten los usuarios, en apego a la normatividad vigente, a efecto de optimizar los recursos para otorgar un servicio satisfactorio','Servicios generales','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(87,'LIDCONFS','Táctico 1','LIDER CONTABILIDAD FISCAL Y FINANCIERA','Nacional','Planear, revisar y coordinar las actividades contables, financieras y tributarias de la Compañía, controlando y verificando los procesos de registro, clasificación y contabilización de las transacciones, con el fin de garantizar que los estados financieros sean confiables y oportunos.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(88,'LIDCUAD','Táctico 1','LIDER DE CUADRILLA','Nacional','Coordinar en campo el recurso humano y técnico entregado por la compañía para alcanzar los objetivos de los proyectos en calidad, costo y oportunidad','Proyectos e ingenieria','COORDINADOR DE PROYECTOS','')
,(89,'LIDPROYE','Táctico 1','LIDER DE PROYECTO','Nacional','Gestionar, supervisar y asegurar la ejecución efectiva de proyectos de desarrollo de software.','Tecnologias de la información y las comunicaciones (TIC)','JEFE DE SISTEMAS','')
,(90,'LIDEREG','Táctico 1','LIDER DE REGULACION','Nacional','Efectuar el monitoreo permanente de los Proyectos de Resolución y normativas en general emitidos por los entes de regulación y control para su respectivo análisis de impactos y comentarios.','Planeación y regulación','JEFE DE PLANEACION','')
,(91,'INGLIDCP','Táctico 1','LIDER NACIONAL CONTROL PERDIDAS','Nacional','Establecer los planes, políticas, procedimientos, controles, estrategias y estructuración necesaria que permitan la disminución de pérdidas no técnicas de Gas Natural de la compañia.','Control pérdidas','JEFE NACIONAL DE SERVICIOS Y CONTROL','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(92,'LIDNALSA','Táctico 1','LIDER NACIONAL SERVICIOS ASOCIADOS','Nacional','Garantizar soluciones técnicas mediante la atención de las necesidades de los clientes internos y externos, a través de la prestación de servicios energéticos, relacionado con visitas, adecuación, y mantenimiento de instalaciones de gas mediante estándares de calidad.','Servicios asociados','JEFE NACIONAL DE SERVICIOS Y CONTROL','')
,(93,'ADMINOMI','Táctico 2','ADMINISTRADOR DE NOMINA I','Nacional','Garantizar, controlar y monitorear adecuadamente los procesos de nómina, bajo las políticas establecidas por la compañía y la normatividad laboral, generando confiabilidad y veracidad en la información.','Relaciones laborales','COORDINADOR DE RELACIONES LABORALES','')
,(94,'ADMISIST','Táctico 2','ADMINISTRADOR DEL SISTEMA','Nacional','Efectuar el análisis y diseño, de nuevas opciones para los sistemas de información y brindar soporte a nivel de hardware y software a los usuarios.','Infraestructura','COORDINADOR DE HARDWARE Y REDES','')
,(95,'ANALAMBI','Táctico 2','ANALISTA AMBIENTAL','Nacional','Planear, establecer e implementar procesos y procedimientos encaminados a dirigir la Gestión Ambiental de la empresa; 
asegurando el cumplimiento de la normatividad ambiental a fin de prevenir y minimizar el impacto ambiental.','HSEQ','JEFE DE HSEQ','')
,(96,'ANALCONT','Táctico 2','ANALISTA CONTABLE','Nacional','Efectuar actividades de análisis, seguimiento y control de la información procesada para revisar, clasificar, codificar, organizar, controlar, elaborar, entregar, liquidar, verificar y registrar sistemáticamente en forma ordenada y oportuna todos los hechos económicos de la compañía de acuerdo con los procesos y procedimientos establecidos, las directrices del jefe inmediato y conforme a las disposiciones contables, fiscales y legales que se apliquen a cada situación.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(97,'ANACOPE','Táctico 2','ANALISTA CONTROL PERDIDAS','Nacional','Elaborar el análisis del comportamiento de los consumos de los diferentes usuarios de la compañía a fin de generar alarmas y propuestas de intervención oportunas que prevengan futuras pérdidas de gas natural para la compañía, así como diseñar e implementar estrategias comerciales para mantener y recuperar usuarios en riesgo.','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(98,'ANALCALI','Táctico 2','ANALISTA DE CALIDAD','Nacional','Administrar, coordinar y gestionar el Sistema de Gestión de Calidad (SGC) Garantizando el adecuado cumplimiento de los estándares y parámetros establecidos en Alcanos de Colombia SA ESP.','HSEQ','JEFE DE HSEQ','')
,(99,'ANALCTRA','Táctico 2','ANALISTA DE CONTRATACION','Nacional','Garantizar que todos los negocios jurídicos se elaboren, suscriban y legalicen en el marco de la ley y las políticas de Alcanos protegiendo los riesgos e intereses de la empresa.','Dirección jurídica','JEFE JURIDICA','')
,(100,'ANALNEGO','Táctico 2','ANALISTA DE NEGOCIOS','Nacional','Consolidar y comunicar información obtenida del cliente, usuarios o expertos al resto del equipo y asegurarse que la 
solución que se desarrolla se ajuste a las necesidades del proyecto.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE PROYECTO','')
,(101,'ANALPROC','Táctico 2','ANALISTA DE PROCESOS','Nacional','Gestionar trabajo con los Líderes de proceso y Directores para definir y validar la operación actual del negocio y diseñar modelos de procesos futuros con participantes de líneas de negocios para construir e implementar mejoras.','HSEQ','JEFE DE HSEQ','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(102,'ANALQA','Táctico 2','ANALISTA DE QA','Nacional','Garantizar el nivel de calidad establecido en el proyecto y ayudar al equipo de desarrollo y demás miembros del proyecto a identificar problemas en una etapa temprana del ciclo de vida del software.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE QA','')
,(103,'ANALTESO','Táctico 2','ANALISTA DE TESORERIA','Nacional','Analizar, vigilar y controlar el recaudo de la 
compañía y realizar seguimiento a comisiones y 
gastos bancarios.','Tesoreria','JEFE DE TESORERIA','')
,(104,'ANALGHUM','Táctico 2','ANALISTA GESTION HUMANA','CentroOperativo','Garantizar el reclutamiento, selección, inducción, capacitación y administración de personal de los Centros Operativos asignados.','Gestión humana','COORDINADOR GESTION HUMANA','')
,(105,'ANAPQRJR','Táctico 2','ANALISTA PQR JUNIOR','Nacional','Emitir respuesta a las peticiones, quejas y reclamos por escritos, presentados por los usuarios dentro del término legal establecido y dando cumplimiento a la normatividad que las regulan','Servicio al cliente','COORDINADOR DE PQR','')
,(106,'ANAPQR','Táctico 2','ANALISTA PQR','Nacional','Emitir respuestas a las peticiones, quejas, reclamos y sugerencias escritos, presentados por los usuarios dentro del término legal establecido y dando cumplimiento a la normatividad que las regulan.','Servicio al cliente','COORDINADOR DE PQR','')
,(107,'ANASOPII','Táctico 2','ANALISTA SOPORTE TECNICO 2','Nacional','Analizar, organizar y gestionar las actividades de servicios asociados, de acuerdo a lo estipulado en la Resolución CREG 059 junio del 2012, Resolución CREG 067 Diciembre del 1995 de la legislación vigente. Así como Administrar el recurso humano de forma estratégica para que se cumpla con los requerimientos de las entidades regulatorias, clientes y OIAS.','Servicios asociados','LIDER NACIONAL SERVICIOS ASOCIADOS','')
,(108,'ANASOPTE','Táctico 2','ANALISTA SOPORTE TECNICO I','Nacional','Analizar, organizar y gestionar las actividades de servicios asociados, de acuerdo a lo estipulado en la Resolución CREG 059 junio del 2012, Resolución CREG 067 Diciembre del 1995 de la legislación vigente. Así como Administrar el recurso humano de forma estratégica para que se cumpla con los requerimientos de las entidades regulatorias, clientes y OIAS.','Redes','JEFE DE REDES','')
,(109,'ANATELEM','Táctico 2','ANALISTA TELEMETRIA','Nacional','Garantizar el seguimiento a la infraestructura de GNC, así como analizar y propender por la eficiencia en el transporte del mismo. Garantizar la comunicación de todas las estaciones descompresoras con el Scada de la central de operaciones, centralizando todas la señales relevantes en el proceso de descompresión para que puedan ser monitoreadas y analizadas con facilidad.','Central de operaciones','COORDINADOR CENTRAL OPERACIONES','')
,(110,'AUDCTRIN','Táctico 2','AUDITOR CONTROL INTERNO','CentroOperativo','Evaluar la implementación, gestión de los procedimientos y políticas estipuladas en la compañía, a través de la realización
de auditorías, que permitan identificar riesgos y oportunidades que contribuyan a un correcto funcionamiento y mejoramiento continuo de los procesos; además de garantizar la implementación del Sistema de Autocontrol y Gestión de Riesgos de Lavado de activos y Financiación del terrorismo, como también el Sistema de protección de datos y privacidad de la información de los grupos de interés y de la Organización.','Control interno','JEFE DE CONTROL INTERNO','')
,(111,'AUDITECN','Táctico 2','AUDITOR TECNICO','CentroOperativo','Colaborar en las actividades de auditoria interna en forma sistemática y oportuna para asegurar que los controles técnicos en cuanto a la cadena de valor, contribuya al desarrollo eficiente y eficaz de los procesos y a la optimización de los resultados de la Compañía.','Auditoria','JEFE DE AUDITORIA INTERNA','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(112,'INGEMETR','Táctico 2','INGENIERO DE METROLOGIA','Nacional','Asegurar el cumplimiento de los planes de control metrológico de todos los equipos de medición de la compañía y apoyar en la gestión gestionar y controlar de la verificación y/o calibración de los medidores residenciales, comerciales, industriales y GNV..','Metrología y estándares','DIRECTOR CALIDAD DE OBRA','')
,(113,'INGSOFTT','Táctico 2','INGENIERO DE SOFTWARE 2','Nacional','Participar integralmente en el análisis, diseño, desarrollo y mantenimiento de los sistemas de información de la Compañía, de acuerdo a las políticas y estándares establecidos y en pro del beneficio de los clientes y funcionarios.','Desarrollo y soporte','COORDINADOR DESARROLLO Y SOPORTE','')
,(114,'INGRESID','Táctico 2','INGENIERO RESIDENTE','Nacional','Planear, dirigir y controlar el proceso constructivo, 
en la ejecución de nuevos proyectos u obras de 
ampliación - prolongación de redes de 
distribución en acero o polietileno con el fin de 
garantizar su correcta ejecución cumpliendo con 
la NTC y hacer cumplir los rendimientos de las 
cuadrillas de trabajo.','Redes','JEFE DE REDES','')
,(115,'INTESISO','Táctico 2','INTERVENTOR SISO','Nacional','Validar que los Contratistas de Alcanos de 
Colombia cuenten con un ambiente laboral 
seguro, mediante el control de causas básicas 
que potencialmente puedan generar 
enfermedades profesionales o accidentes de 
trabajo.','Interventoria','JEFE DE INTERVENTORIA','')
,(116,'INTERVEN','Táctico 2','INTERVENTOR','Nacional','Coordinar las interventorías a las actividades 
asignadas a los contratistas integrales.','Interventoria','JEFE DE INTERVENTORIA','')
,(117,'PROFCOMG','Táctico 2','PROFESIONAL CONTABLE DE IMPUESTOS','Nacional','Analizar, preparar, revisar, organizar, elaborar y presentar a nivel nacional y territorial las liquidaciones de impuestos, requerimientos y demás información tributarias según la normatividad vigente.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(118,'PRCONTNI','Táctico 2','PROFESIONAL CONTABLE NIFF','Nacional','Analizar, preparar, revisar, organizar, elaborar y presentar a nivel nacional y territorial las liquidaciones de impuestos, requerimientos y demás información tributarias según la normatividad vigente.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(119,'PROFCPER','Táctico 2','PROFESIONAL CONTROL PERDIDAS','Nacional','Contribuir en la recuperación de los valores de la empresa por concepto de cobros por investigación, resultado de las anomalías que se encuentren en equipos de medición, redes y acometidas atribuibles al usuario que generan pérdidas de gas natural.','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(120,'PROBIENL','Táctico 2','PROFESIONAL DE BIENESTAR LABORAL','Nacional','Diseñar, desarrollar e implementar a nivel nacional el Programa de Bienestar y comunicaciones internas, generando alternativas de mejora para la satisfacción y calidad de vida de los colaboradores.','Bienestar laboral','DIRECTOR DE GESTION HUMANA','')
,(121,'PROPQR','Táctico 2','PROFESIONAL PQR','Nacional','Gestionar las peticiones, quejas, reclamos y sugerencias presentados por los usuarios de manera escrita y/o los recibidos de entidades externas que tengan relación con el servicio público, dentro del término legal establecido y dando cumplimiento a las normas que las regulan.','Servicio al cliente','COORDINADOR DE PQR','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(122,'PROCAPDE','Táctico 2','PROFESIONAL DE CAPACITACION Y DESARROLLO','Nacional','Diseñar, desarrollar e implementar el programa de capacitación orientado a la formación especializada de personal en el sector gas y otros, que garanticen el desarrollo y el fortalecimiento de competencias.','Capacitación y desarrollo','DIRECTOR DE GESTION HUMANA','')
,(123,'COORPQRS ','Táctico 1','COORDINADOR DE PQR','Nacional','Organizar, coordinar y controlar el proceso de respuesta y notificación a las PQR de la compañía, relacionadas con el servicio público. Garantizar que éstas se contesten bajo los términos legales.','Servicio al cliente','JEFE SERVICIO AL CLIENTE','')
,(124,'JEFECOMG','Táctico 1','JEFE COMERCIALIZACION DE GAS','Nacional','Gestionar estratégicamente y proponer la optimización de las Compras-Costos y las Ventas a Grandes Clientes
(Industrias y GNCV- Programa Bono-Vehicular), de suministro y/o transporte de gas natural; y Masificar las ventas en el
Mercado Secundario; Venta de conexiones y/o instalaciones y Programa CRM; generando beneficio a todos los grupos de
interés de la compañía. Fortalecer los procesos y el equipo de trabajo, a partir de las competencias corporativas y/o
regulatorias.','Comercialización de gas','DIRECTOR COMERCIAL','')
,(125,'ANALCOMP ','Táctico 2','ANALISTA DE COMPRAS','Nacional','Desarrollar actividades de selección y evaluación de proveedores y contratistas, para el suministro de los bienes y servicios requeridos por las diferentes áreas de la empresa; garantizando la trasparencia en los procesos, el cumplimiento de las especificaciones y la satisfacción de las necesidades de la compañía, cumpliendo con los parámetros de seguridad y calidad establecidos.','Compras y contratación','JEFE DE COMPRAS','')
,(126,'INGEDGAS','Táctico 2','INGENIERO DE GAS','Nacional','Colaborar con la dirección comercial en todos los procesos de ventas de Instalaciones Industriales e incrementos de consumo de gas.','Comercialización de gas','JEFE COMERCIALIZACION DE GAS','')
,(127,'DIREAD','Estratégico','DIRECTOR ADMINISTRATIVO Y FINANCIERO','Nacional','Garantizar la adecuada gestión administrativa y mantener las variables financieras controladas y equilibradas para alcanzar el cumplimiento de los objetivos y la sostenibilidad organizacional.','Dirección administrativa y financiera','GERENTE GENERAL','')
,(128,'DIRABAST','Estratégico','DIRECTOR DE ABASTECIMIENTO','Nacional','Planear, definir y controlar la gestión logística y abastecimiento de bienes y servicios, para brindar soporte oportuno a los procesos, en cumplimiento de los estándares de calidad y procedimientos establecidos.','Dirección de abastecimiento','GERENTE GENERAL','')
,(129,'DIRDEGHU','Estratégico','DIRECTOR DE GESTION HUMANA','Nacional','Dirigir los procesos de vinculación, desarrollo, administración de nómina, relaciones sindicales y fidelización que
aseguren un talento humano comprometido, innovador y eficiente para el logro de los objetivos organizacionales,
cumpliendo con los requisitos del Sistema Integrado de Gestión, los legales y reglamentarios. Mantener actualizado y
alineado los planes de gestión de talento humano: selección, vinculación, promoción y calificación, estructura de salarios,
compensación, gestión de objetivos y desempeño, bienestar y calidad de vida entre otros.','Dirección de gestión humana','GERENTE GENERAL','')
,(130,'GERENTCOP','Estratégico','GERENTE DE CentroOperativo','CentroOperativo','- Dirigir y controlar, en el CentroOperativo a su cargo, la operacionalización de los planes, políticas, sistemas, procedimientos y normas acordados con la Dirección Nacional para lograr los resultados técnicos, administrativos, financieros comerciales y de servicio al cliente esperados.
- Representar a la Compañía en la región y mantener relaciones con autoridades, entidades gremiales y organizaciones para posicionarla como una empresa de excelencia operacional.','Gerencia CO','GERENTE GENERAL','')
,(131,'GTEGRAL','Estratégico','GERENTE GENERAL','Nacional','Representar Legalmente a Alcanos de Colombia ante terceros y toda clase de autoridades del orden administrativo o jurídico; garantizando los resultados a través del planteamiento de las estrategias encaminadas a cumplir la misión y visión, con el fin de conseguir objetivos y metas de la organización.','Gerencia general','','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(132,'JEFEAUDI','Estratégico','JEFE DE AUDITORIA INTERNA','Nacional','Planear, elaborar y desarrollar el plan de trabajo de auditoría interna de manera independiente y objetiva, con el propósito de agregar valor y mejorar el ambiente de control a partir de la evaluación de los procesos de gobierno corporativo, control interno y gestión del riesgo.','Auditoria','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(133,'JFNCONS','Estratégico','JEFE NACIONAL DE CONSTRUCCIONES','Nacional','Gestionar la integración y consolidación del proceso constructivo de instalaciones internas, montaje de centros de medición y regulación para nuevos usuarios, bajo los lineamientos de calidad, tiempo y costo a nivel compañía; con el objetivo de apalancar las metas establecidas por la organización, propendiendo por el cumplimiento de la normativa técnica, la gestión del conocimiento, el análisis de costo-beneficio de los procesos constructivos y la selección de materiales y mejores técnicas que coadyuven a la mejora continua.','Construcciones','DIRECTOR SERVICIOS TECNICOS','')
,(134,'JEFENSCT','Estratégico','JEFE NACIONAL DE SERVICIOS Y CONTROL','Nacional','Establecer estrategias de desarrollo y ejecutar el seguimiento a los planes, políticas, procedimientos, controles y estructura, necesarios para lograr el cumplimiento de los indicadores claves de los procesos adelantados por las áreas de Servicios asociados y Control Pérdidas.','Dirección de servicios técnicos','DIRECTOR SERVICIOS TECNICOS','')
,(135,'AGENTCEN','Operativo','AGENTE DE CONTAC CENTER','Nacional','Revisar y registrar en el sistema las solicitudes de los usuarios en aras de dar alternativas de solución efectivas a los mismos. Como también, realizar la gestión comercial, programación y seguimiento de las instalaciones para su respectiva construcción.','Contact center','COORDINADOR CONTAC CENTER','SUPERVISOR CONTAC CENTER')
,(136,'ALMACENI','Operativo','ALMACENISTA','CentroOperativo','Realizar la administración, custodia y garantia de las entradas y salidas de los materiales, insumos y suministros del almacén asignado, así como responder por el correcto almacenamiento y distribución del inventario.','Gestión de almacenes e inventarios','JEFE ADMINISTRACION ACTIVOS','')
,(137,'ASESCOME','Operativo','ASESOR COMERCIAL','CentroOperativo','Obtener nuevos usuarios, persuadiendolos a comprar instalaciones internas para el suministro de gas natural, ofreciendo la información exacta sobre el servicio, costos, precios, uso, garantías y ventajas del producto ofrecido por la organización.','Mercadeo y ventas','COORDINADOR DE VENTAS','GERENTE DE CentroOperativo')
,(138,'ASIADTCO','Operativo','ASISTENTE ADM DE CentroOperativo','CentroOperativo','Soportar a la Gerencia en la revisión y control de facturas, cuentas, lista de chequeo, etc que lleguen al CentroOperativo, así como la elaboración y manejo de cajas menores y de gastos de viaje. Organizar y llevar los archivos correspondientes del área, recepcionar y realizar llamadas telefónicas y atender a las personas que visitan a Gerencia General y Gerencia de CentroOperativo. Apoyar a Gestión Humana en la vinculación y retiro de empleados, así como en las actividades programadas por la misma.','Gerencia CO','GERENTE DE CentroOperativo','')
,(139,'ASDICOME','Operativo','ASISTENTE DE DIRECCION COMERCIAL','Nacional','Ejecutar, atender y asistir actividades que tenga relación con el área comercial para garantizar el cumplimiento de estas.','Dirección comercial','DIRECTOR COMERCIAL','')
,(140,'ASISERVT','Operativo','ASISTENTE SERVICIOS TECNICOS Y C/CION','Nacional','Realizar el seguimiento Integral al desarrollo de los contratos asociados a las actividades de la Dirección. Asistir, atender y coordinar actividades de la Dirección de Servicios Técnicos.','Dirección de servicios técnicos','DIRECTOR SERVICIOS TECNICOS','')
,(141,'AUXADO&M','Operativo','AUXILIAR ADMINISTRATIVO O Y M','CentroOperativo','Ejecutar, coordinar, atender y asistir las actividades que tengan relación con el área de operación y mantenimiento para garantizar el cumplimiento de las mismas. Cumplir con las tareas establecidas para el cumplimiento de los procesos establecidos en la compañía.','Operación y mantenimiento','COORDINADOR DE O Y M','GERENTE DE CentroOperativo')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(142,'AUXADMOT','Operativo','AUXILIAR ADMINISTRATIVO OTI','CentroOperativo','Gestionar la logística y la disponibilidad de recursos con el fin de garantizar las actividades del proceso de inspección del OTI, Manejo y control de la información de la operatividad y de la administración del personal.','Organismo técnico de inspección y certificación','COORDINADOR OTI','GERENTE DE CentroOperativo')
,(143,'AUXADTVO','Operativo','AUXILIAR ADMINISTRATIVO','CentroOperativo','Dar apoyo a los procesos y actividades del CentroOperativo y/o del área a la que es asignado cumpliendo con todas las instrucciones y directrices encomendadas.','Gerencia CO','GERENTE DE CentroOperativo','')
,(144,'AUXCONTI','Operativo','AUXILIAR CONTABLE I','Nacional','Realizar actividades básicas y de apoyo para recibir, revisar, recopilar, clasificar, organizar, elaborar, entregar, verificar y registrar sistemáticamente en forma ordenada y oportuna todos los hechos económicos de la compañía de acuerdo con los procesos, procedimientos y políticas establecidos, las directrices del jefe inmediato y conforme a las disposiciones contables, fiscales y legales que se apliquen a cada situación.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
,(145,'AUXACTFI','Operativo','AUXILIAR DE ACTIVOS FIJOS','Nacional','Asesorar, organizar y vigilar los activos fijos de la compañía y apoyo a la prestación de servicios generales para el desarrollo de las actividades de las diferentes áreas','Gestión de almacenes e inventarios','JEFE ADMINISTRACION ACTIVOS','')
,(146,'AUXIALMA','Operativo','AUXILIAR DE ALMACEN','CentroOperativo','Adecuar, almacenar, clasificar y ordenar, los materiales y suministros que se manejan dentro del almacén, así como responder por la custodia del inventario en el almacén','Gestión de almacenes e inventarios','JEFE ADMINISTRACION ACTIVOS','')
,(147,'AUXICAMP','Operativo','AUXILIAR DE CAMPO','CentroOperativo','Dar soporte operativo a facturación en los procedimientos asociados con toma de lecturas, entrega de facturas y otras afines','Facturación','SUPERVISOR CAMPO','JEFE DE FACTURACION')
,(148,'AUXCARTE','Operativo','AUXILIAR DE CARTERA','CentroOperativo','Realizar la planificación, ejecutar y participar en las actividades necesarias para el cumplimiento de las metas trazadas dentro del proceso de cartera y que contribuyan al logro de los objetivos de la organización.','Cartera','JEFE DE CARTERA','')
,(149,'AUXICOMP','Operativo','AUXILIAR DE COMPRAS','Nacional','Asistir el proceso de compras y abastecimiento de materiales, herramientas y equipos necesarios para el desarrollo operacional de la compañía.','Compras y contratación','JEFE DE COMPRAS','')
,(150,'AUXCOINV','Operativo','AUXILIAR DE CONTROL DE INVENTARIOS','Nacional','Resguardar y garantizar las existencias del inventario y el buen uso de los materiales en las operaciones de la empresa.','Gestión de almacenes e inventarios','COORDINADOR DE CONTROL DE INVENTARIOS','')
,(151,'AUXILGNC','Operativo','AUXILIAR DE GNC','Nacional','Diligenciar y realizar el mantenimiento a los módulos; inspeccionar el sistema operativo de compresores y controlar despachos de gas, mediante el sistema de GNC.','Gas natural comprimido','COORDINADOR DE GNC','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(152,'AUXIHSEQ','Operativo','AUXILIAR DE HSEQ','Nacional','Realizar el acompañamiento en la implementación y mantenimiento de los procesos existentes en el marco del SGC de la compañía.','HSEQ','JEFE DE HSEQ','')
,(153,'AUXMERCA','Operativo','AUXILIAR DE MERCADEO','Nacional','Dar apoyo a la coordinación de mercadeo en el diseño de piezas publicitarias, edición de audios y videos y diseño de presentaciones institucionales.','Mercadeo y ventas','COORDINADOR DE MERCADEO','')
,(154,'AUXIOBRA','Operativo','AUXILIAR DE OBRA','CentroOperativo','Asistir al oficial de obra en las actividades de construcción de obra civil, en la ejecución de nuevos proyectos u obras de ampliación - prolongación de redes de distribución en acero o polietileno.','Redes','COORDINADOR DE REDES','GERENTE DE CentroOperativo')
,(155,'AUXSERGE','Operativo','AUXILIAR DE SERVICIOS GENERALES','Nacional','Dar orden y control a la prestación de servicios generales para el desarrollo de las actividades de las diferentes áreas, mantener el archivo de la compañía y realizar el debido seguimiento.','Servicios generales','JEFE SERVICIOS GENERALES','')
,(156,'AUXIVENT','Operativo','AUXILIAR DE VENTAS','CentroOperativo','Revisar y grabar las ventas hechas en la zona, controlando y verificando que se hayan realizado dentro de los procesos establecidos por la Gerencia, al igual que el manejo general de la documentación utilizada en el área. Atender las ventas que se generen en las oficinas por visitas de usuarios potenciales.','Mercadeo y ventas','COORDINADOR DE VENTAS','GERENTE DE CentroOperativo')
,(157,'AUXPQR','Operativo','AUXILIAR PQR','Nacional','Realizar el control a través de SICOM y los archivos virtuales, todos los escritos y peticiones que se manejan en el grupo de PQR, dando el trámite correspondiente en los tiempos establecidos a fin de garantizar su efectiva notificación y archivo de expedientes.','Servicio al cliente','COORDINADOR DE PQR','')
,(158,'AUXSOPOM','Operativo','AUXILIAR SOPORTE OBRA MOVIL','CentroOperativo','Dar soporte para la implementación y seguimiento del uso del aplicativo para descarga de mano de obra, materiales, reporte novedades, inspección y certificación de instalaciones en tiempo real mediante la APP Alcanos Obra.','Construcciones','JEFE NACIONAL DE CONSTRUCCIONES','')
,(159,'AUXTREME','Operativo','AUXILIAR TEC DE RECEPCION DE EMERG','Nacional','Garantizar que se dé un adecuado trámite a las emergencias y/o pqr´s de suspensión por defecto crítico que se presentan en las diferentes infraestructuras que conforman el sistema de distribución de gas natural.','Central de operaciones','COORDINADOR CENTRAL OPERACIONES','')
,(160,'AUXICONP','Operativo','AUXILIAR TECNICO CONTROL DE PERDIDAS','CentroOperativo','Verificar en campo posibles anomalías por conductas fraudulentas e incumplimientos al contrato de prestación de servicio de gas natural, en equipos de medición, regulación, redes y acometidas que causen pérdidas de gas natural, soportando bajo parámetros técnicos y normativos las novedades encontradas para proceder a realizar trámites de acuerdo con los procesos establecidos por la compañía; de igual manera contribuir con los controles que el área Control Pérdidas considere necesario implementar en los usuarios.','Control pérdidas','SUPERVISOR CONTROL PERDIDAS','GERENTE DE CentroOperativo')
,(161,'AUXTCGNS','Operativo','AUXILIAR TECNICO DE GNS','CentroOperativo','Realizar las funciones técnico operativas que se requieran para que la planta de Gas Natural Sustituto (GNS) opere de forma segura y continua.','Operación y mantenimiento','COORDINADOR DE O Y M','GERENTE DE CentroOperativo')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(162,'AUXTEMAN','Operativo','AUXILIAR TECNICO DE MANTENIMIENTO','CentroOperativo','Ejecutar la programación de mantenimiento para los activos de distribución de las Estaciones y Red de Acero de ALCANOS DE COLOMBIA S.A. E.S.P., buscando aumentar su eficiencia en la distribución, minimizando los costos de operación y mantenimiento, además de satisfacer las necesidades de los usuarios, en donde la responsabilidad no recae solo en el departamento de mantenimiento sino en toda la estructura de la empresa.','Operación y mantenimiento','COORDINADOR DE MANTENIMIENTO','')
,(163,'AUXTEMET','Operativo','AUXILIAR TECNICO DE METROLOGIA','Nacional','Verificar las condiciones de exactitud de los equipos de metrología que posee la compañía para ejecutar labores técnico – operativo.','Metrología y estándares','INGENIERO DE METROLOGIA','')
,(164,'AUXTEPER','Operativo','AUXILIAR TECNICO DE PERDIDAS','CentroOperativo','Ejecutar todas las actividades técnicas tendientes a minimizar las pérdidas operacionales de la compañía, levantando en campo la información conducente para el cobro de indemnizaciones, medidores y otros rubros autorizados contractualmente a través del C.C.U, por la comisión de conductas fraudulentas e incumplimientos al contrato de prestación de servicios y que se encuentran a cargo de legalización por parte del área de INV.','Control pérdidas','SUPERVISOR CONTROL PERDIDAS','GERENTE DE CentroOperativo')
,(165,'AUXTESER','Operativo','AUXILIAR TECNICO DE SERVICIOS','CentroOperativo','Realizar la supervisión y garantizar la calidad de obra de los contratistas e instaladores de la compañía y mantener los niveles de servicio establecidos.','Construcciones','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(166,'AYOBRO&M','Operativo','AYUDANTE DE OBRA O&M','CentroOperativo','Garantizar el cumplimiento, la normatividad y los procedimientos establecidos en la ETR 0302.','Operación y mantenimiento','COORDINADOR DE O Y M','GERENTE DE CentroOperativo')
,(167,'AYUDOBRA','Operativo','AYUDANTE DE OBRA','CentroOperativo','Garantizar la ubicación del centro de medición cumpliendo con la normatividad y los procedimientos establecidos','CONSTRUCCIONES','COORDINADOR DE CONSTRUCCIONES','GERENTE DE CentroOperativo')
,(168,'COMPJUNI','Operativo','COMPRADOR JUNIOR','Nacional','Garantizar el cumplimiento efectivo del proceso de compras y abastecimiento de materiales, herramientas y equipos necesarios para el desarrollo operacional de la compañía.','Compras y contratación','JEFE DE COMPRAS','')
,(169,'DESARROL','Operativo','DESARROLLADOR','Nacional','Colaborar con el proceso de programación/implementación teniendo como entrada las especificaciones de software, arquitectura y diseño y ajustándose a tiempos y estándares de calidad y trabajo de la compañía y del proyecto.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE PROYECTO','')
,(170,'DIGIDOBR','Operativo','DIGITADOR DE OBRA','CentroOperativo','Realizar el ingreso de la información relacionada con el área Técnica al sistema de la compañía. Además de ingresar información a la base de datos de BASEGAS y los softwares corporativos que amerite, con el propósito de realizar los respectivos informes.','Redes','JEFE DE REDES','')
,(171,'DIGIPQRS','Operativo','DIGITADOR DE PQRS','CentroOperativo','Realizar la digitación de las PQRS y solicitudes de manera oportuna y clara','Servicio al cliente','GERENTE DE CentroOperativo','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(172,'GESINSPE','Operativo','GESTOR DE INSPECCIONES','CentroOperativo','Gestionar soluciones a instalaciones que no se han certificado, comunicación con líderes, administradores de multifamiliares, acompañamiento en campo, atención y solución de PQRs, coordinar reparaciones y certificaciones entre el área de construcciones y el organismo de inspección.','Organismo técnico de inspección y certificación','DIRECTOR CALIDAD DE OBRA','')
,(173,'GESTORCO','Operativo','GESTOR DE LA CONFIGURACION','Nacional','Realizar la administración, organización y control sistemático de los cambios en los documentos, códigos y otras entidades, junto con la administración de los ambientes de trabajo durante el ciclo de vida del desarrollo de software.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE PROYECTO','')
,(174,'GESTECON','Operativo','GESTOR TECNICO DE CONSTRUCCIONES','CentroOperativo','Gestionar las actividades que permitan garantizar el adecuado desempeño y productividad, de cuadrillas propias y de contratistas, asegurando la calidad y oportunidad en la conexión de nuevos usuarios; manteniendo un canal de comunicación y reporte permanente entre el Coordinador y Supervisores de Construcciones.','Construcciones','COORDINADOR DE CONSTRUCCIONES','')
,(175,'INSTRUME','Operativo','INSTRUMENTISTA','CentroOperativo','Ejecutar la programación de mantenimiento para los activos de distribución de las Estaciones y Red de Acero de ALCANOS DE COLOMBIA S.A. E.S.P., buscando aumentar su eficiencia en la distribución, minimizando los costos de operación y mantenimiento, además de satisfacer las necesidades de los usuarios, en donde la responsabilidad no recae solo en el departamento de mantenimiento sino en toda la estructura de la empresa.','Operación y mantenimiento','COORDINADOR DE MANTENIMIENTO','')
,(176,'MAESOBRA','Operativo','MAESTRO DE OBRA','CentroOperativo','Ejecutar las actividades de construcción de 
obras civiles de acuerdo a la programación 
establecida.','Redes','INGENIERO RESIDENTE','')
,(177,'OFICOBRA','Operativo','OFICIAL DE OBRA','CentroOperativo','Asistir al maestro de obra en las actividades de construcción de obra civil, en la ejecución de nuevos proyectos u obras de ampliación - prolongación de redes de distribución en acero o polietileno e instalaciones internas.','Redes','COORDINADOR DE REDES','')
,(178,'PEGADOR','Operativo','PEGADOR II','CentroOperativo','Garantizar seguridad y eficiencia en los sistemas operativos de los gasoductos, que conlleve a una excelente prestación del servicio y a la continuidad de este.','REDES','COORDINADOR DE REDES','GERENTE DE CentroOperativo')
,(179,'PRACTJUR','Operativo','PRACTICANTE JURIDICO','Nacional','Recibir, resguardar, dar trámite y hacer seguimiento a los documentos que se alleguen a la Jefatura Jurídica, ejecutando actividades de reporte de información, archivo y custodia de documentos, revisión procesos de manera física y virtual en términos procesales, contabilización de términos en los diferentes procesos, vigilancia y control procesal, visita a juzgados y demás actuaciones procesales que se requieran y soliciten por intermedio del área jurídica.','Dirección jurídica','DIRECTOR JURIDICO','')
,(180,'RECEPCIO','Operativo','RECEPCIONISTA','CentroOperativo','Garantizar la satisfacción de las necesidades de comunicación del personal de la compañía, operando una central telefónica pequeña, atendiendo al público en sus requerimientos de información y entrevistas con el personal, ejecutando y controlando la recepción y despacho de la correspondencia, para servir de apoyo a las actividades de la organización.','Gerencia CO','GERENTE DE CentroOperativo','')
,(181,'SUBCAMPO','Operativo','SUPERVISOR CAMPO','CentroOperativo','Realizar la planificación de acuerdo con los recursos asignados las actividades que dan cumplimiento a los indicadores de gestión y realizar seguimiento continuo de las labores administrativas y de campo.','Facturación','JEFE DE FACTURACION','GERENTE DE CentroOperativo')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(182,'SUPERCAR','Operativo','SUPERVISOR CARTOGRAFICO','Nacional','Realizar la georreferenciación en campo de la información de activos de distribución, bases prediales, usuarios conectados y potenciales; provenientes de la ejecución de nuevos proyectos, ampliaciones de red, actividades del área de operación y mantenimiento y/o revisión de información existente.','Cartografia','JEFE DE CARTOGRAFIA','')
,(183,'SUPVCAMP','Operativo','SUPERVISOR DE CAMPO','CentroOperativo','Realizar la planificación de acuerdo con los recursos asignados las actividades que dan cumplimiento a los indicadores de gestión y realizar seguimiento continuo de las labores administrativas y de campo.','Facturación','JEFE DE FACTURACION','GERENTE DE CentroOperativo')
,(184,'SUPINTER','Operativo','SUPERVISOR DE INTERVENTORIA','Nacional','Verificar las actividades desarrolladas por los contratistas acorde al objeto y exigencias estipuladas contractualmente.','Interventoria','SUPERVISOR DE INTERVENTORIA','')
,(185,'SUPVOTI','Operativo','SUPERVISOR OTI','CentroOperativo','Realizar el trabajo de supervisión de campo relacionado con los procesos de inspección de instalaciones nuevas, modificadas y en servicio de gas natural y en lo que tiene que ver con las actividades desarrolladas por los Inspectores; como también atender y dar solución oportuna en campo a las quejas y apelaciones derivadas del proceso de inspección','Organismo técnico de inspección y certificación','COORDINADOR OTI','GERENTE DE CentroOperativo')
,(186,'TECINDCO','Operativo','TECNICO INDUSTRIALES Y COMERCIALES','CentroOperativo','Realizar proceso de validación y visitas en campo para evaluar las condiciones técnicas de las instalaciones internas; así como identificar posibles anomalías en equipos de medición, regulación redes y acometidas que estén causando pérdidas significativas de gas natural para usuarios comerciales, industriales y especiales. Apoyar en procesos de capacitación al equipo de trabajo cuando se requiera. 
','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(187,'APSELECT','Operativo','APRENDIZ SENA ESTAPA LECTIVA','CentroOperativo','Dar apoyo en el área la cual sea asignada para realizar su etapa practica','Gestión humana','COORDINADOR GESTION HUMANA','')
,(188,'PRACUNIV','Operativo','PRACTICANTE UNIVERSITARIO','CentroOperativo','Dar apoyo en el área la cual sea asignada para realizar sus practicas profesionales','Gestión humana','DIRECTOR DE GESTION HUMANA','')
,(189,'CONDUCTS','Operativo','CONDUCTOR SERVICIOS GENERALES','CentroOperativo','Conducir el vehículo asignado con el objetivo de apoyar la gestión del CentroOperativo al que pertenecen. Dicha conducción debe realizarse responsablemente y respetando las normas de tránsito existentes.','Servicios generales','JEFE SERVICIOS GENERALES','')
,(190,'SUPHSEQ','Operativo','SUPERVISOR HSEQ','CentroOperativo','Garantizar el mantenimiento y mejoramiento continuo del Sistema Integrado de gestión de la compañía a través de la ejecución y desarrollo de actividades que promuevan de forma oportuna la calidad de vida de nuestros clientes internos, externos y partes interesadas de la Organización.','HSEQ','JEFE DE HSEQ','')
,(192,'COORCART','Táctico 1','COORDINADOR DE CARTERA','CentroOperativo','Garantizar el cumplimiento al presupuesto de cartera de los municipios a cargo, logrando disminuir los índices de morosidad con eficiencia mediante el manejo adecuado de los recursos asignados.','Cartera','JEFE DE CARTERA','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(193,'COORCONS','Táctico 1','COORDINADOR DE CONSTRUCCIONES','CentroOperativo','Coordinar la construcción de acometidas e instalaciones internas para gas domiciliario.','Construcciones','GERENTE DE CentroOperativo','JEFE NACIONAL DE CONSTRUCCIONES')
,(194,'COORMANT','Táctico 1','COORDINADOR DE MANTENIMIENTO','Nacional','Garantizar el cumpliento del plan de mantenimiento para los activos de distribución de las Estaciones y Red de Acero de
ALCANOS DE COLOMBIA S.A. E.S.P.,buscando aumentar su eficiencia en la distribución, minimizando los costos de mantenimiento, además de satisfacer las necesidades de los usuarios, en donde la responsabilidad no recae solo en el departamento de mantenimiento sino en toda la estructura de la empresa.','Operación y mantenimiento','LIDER DE MANTENIMIENTO','')
,(195,'COORDMER','Táctico 1','COORDINADOR DE MERCADEO','Nacional','Facilitar estrategias efectivas e integrales de mercadeo y publicidad que sumen valor para el posicionamiento de la marca.','Mercadeo y ventas','DIRECTOR COMERCIAL','')
,(196,'COORED','Táctico 1','COORDINADOR DE REDES','CentroOperativo','Coordinar, dirigir, ejecutar el desarrollo físico de nuevos proyectos de suministro de gas natural, mediante la construcción de redes de distribución e instalaciones residenciales, comerciales, industriales y estaciones de GNV.','Redes','GERENTE DE CentroOperativo','JEFE DE REDES')
,(197,'COORSERG','Táctico 1','COORDINADOR DE SERVICIOS GENERALES','Nacional','Planear, organizar, dirigir y controlar la prestación de servicios generales para el desarrollo de las actividades de las diferentes áreas y mantener el archivo de la compañía.','Servicios generales','JEFE SERVICIOS GENERALES','')
,(198,'COORDESO','Táctico 1','COORDINADOR DESARROLLO Y SOPORTE','Nacional','Supervisar y coordinar las tareas de análisis, diseño, desarrollo y mantenimiento de los sistemas de información de la Compañía, de acuerdo a las políticas y estándares establecidos, garantizando su oportunidad y calidad.','Desarrollo y soporte','JEFE DE SISTEMAS','')
,(199,'COORED1','Táctico 1','COORDINADOR REDES','CentroOperativo','Coordinar, dirigir, ejecutar el desarrollo físico de nuevos proyectos de suministro de gas natural, mediante la construcción de redes de distribución e instalaciones residenciales, comerciales, industriales y estaciones de GNV.','Redes','GERENTE DE CentroOperativo','JEFE DE REDES')
,(200,'FUNOMINA','Táctico 1','FUNCIONAL NOMINA','Nacional','Contribuir en la creación, implementación y ejecución efectiva de proyectos de desarrollo de software.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE PROYECTO','')
,(201,'JEFCARTO','Táctico 1','JEFE DE CARTOGRAFIA','Nacional','Planear, dirigir, controlar y coordinar todas las actividades y procesos ejecutados por el personal del departamento con el fin de construir y mantener la base de la cartografía de la compañía que permita asegurar el soporte geográfico a las áreas que así lo requieran.','Cartografia','DIRECTOR TECNICO','')
,(202,'JEFCONTA','Táctico 1','JEFE DE CONTABILIDAD','Nacional','Programar, analizar, dirigir, coordinar, controlar el movimiento contable, financiero y de costos de la Compañía, de acuerdo a las normas contables, financieras, fiscales, administrativas y legales vigentes, con el fin de presentar oportuna y fielmente los Estados Financieros de la Entidad.','Contabilidad e impuestos','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(203,'JEFEFACT','Táctico 1','JEFE DE FACTURACION','Nacional','Establecer los planes, políticas, procedimientos, controles y estructura necesarios para llevar a cabo los procesos de facturación.','Facturación','DIRECTOR COMERCIAL','')
,(204,'JEFEGNC','Táctico 1','JEFE DE GNC','Nacional','Establecer los planes, políticas, procedimientos, controles y estructura necesarios, que permitan garantizar que la distribución mediante el sistema de GNC se realice de manera permanente, confiable y segura. Propender por nuevas alternativas de respaldo y distribución, que
garanticen la continuidad del servicio en los municipios atendidos.','Gas natural comprimido','DIRECTOR TECNICO','')
,(205,'JEFEHSEQ','Táctico 1','JEFE DE HSEQ','Nacional','Asegurar la implementación, mantenimiento y mejoramiento continuo del Sistema Integrado de Gestión de Seguridad, Salud, Medio Ambiente y Calidad de la compañía; a través de la planeación y coordinación de los programas alineados a la normatividad legal vigente, satisfaciendo de forma oportuna las necesidades y expectativas de los clientes internos y externos de la Organización.','HSEQ','DIRECTOR DE GESTION HUMANA','')
,(206,'JEFEO&M','Táctico 1','JEFE DE OPERACIÓN Y MANTENIMIENTO','Nacional','Establecer y administrar los planes, políticas, procedimientos, controles y estructura necesaria, que permitan de forma segura y rentable la operación técnica y mantenimiento de la infraestructura de la compañía, comprendida por: Redes de polietileno, redes de acero , Estaciones de regulación y medición (EDD ERM, CITY GATE´s, COMPRESORAS Y DESCOMPRESORAS), y equipos en general; a fin de garantizar una alta disponibilidad y confiabilidad en la prestación del servicio de distribución de Gas Natural.','Operación y mantenimiento','DIRECTOR TECNICO','')
,(207,'JEFPROY','Táctico 1','JEFE DE PROYECTOS','Nacional','Coordinador el recurso humano y técnico entregado por la compañía para alcanzar los objetivos de los proyectos en calidad, costo y oportunidad, teniendo un excelente relacionamiento con clientes internos y externos.','Proyectos e ingenieria','DIRECTOR TECNICO','')
,(208,'JEFEREDE','Táctico 1','JEFE DE REDES','Nacional','Coordinar, dirigir, ejecutar el desarrollo físico de nuevos proyectos de suministro de gas natural, mediante la construcción de redes de distribución e instalaciones residenciales, comerciales, industriales y estaciones de GNV.','Redes','DIRECTOR TECNICO','')
,(209,'JEFETESO','Táctico 1','JEFE DE TESORERIA','Nacional','Administrar y manejar de manera eficaz y adecuada los fondos de la Empresa, realizar pagos de las obligaciones, mantener en custodia títulos valores y realizar operaciones con el sistema financiero, así mismo mantener información actualizada de sus actividades y presentar los informes requeridos.','Tesoreria','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(210,'JESERCLI','Táctico 1','JEFE SERVICIO AL CLIENTE','Nacional','Garantizar la prestación del Servicio al Cliente, orientado a brindar una excelente atención a través de los diferentes canales de comunicación dispuestos por la empresa para este fin. Asegurando que las PQRS sean atendidas de manera efectiva y oportuna, de acuerdo a los procedimientos y normas aplicables vigentes; cumpliendo con las expectativas y satisfacción del cliente.','Servicio al cliente','DIRECTOR COMERCIAL','')
,(211,'LIDCONST','Táctico 1','LIDER DE CONSTRUCCIONES MDO ABIERTO','Nacional','Establecer y ejecutar el seguimiento a los planes, políticas, procedimientos, controles y estructura; necesarios para lograr el cumplimiento de los indicadores claves de los procesos adelantados por el área de construcciones en los 9 centros operativos.','Construcciones','JEFE NACIONAL DE CONSTRUCCIONES','')
,(212,'LIDERMTO','Táctico 1','LIDER DE MANTENIMIENTO','Nacional','Implementar el plan de mantenimiento para todos los activos de distribución de ALCANOS DE COLOMBIA S.A. E.S.P., bajo una filosofía preventiva basada en el ciclo de mejoramiento continuo PHVA (planear, hacer, verificar y actuar), buscando aumentar su eficiencia en la distribución, minimizando los costos de mantenimiento, además de satisfacer las necesidades de los usuarios.','Operación y mantenimiento','JEFE DE OPERACIÓN Y MANTENIMIENTO','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(213,'LIDERMTO','Táctico 1','LIDER DE MANTENIMIENTO','Nacional','Implementar el plan de mantenimiento para todos los activos de distribución de ALCANOS DE COLOMBIA S.A. E.S.P., bajo una filosofía preventiva basada en el ciclo de mejoramiento continuo PHVA (planear, hacer, verificar y actuar), buscando aumentar su eficiencia en la distribución, minimizando los costos de mantenimiento, además de satisfacer las necesidades de los usuarios.','Operación y mantenimiento','JEFE DE OPERACIÓN Y MANTENIMIENTO','')
,(214,'LIDERQA','Táctico 1','LIDER DE QA','Nacional','Garantizar que el producto software cumpla con los criterios de calidad (rendimiento, usabilidad, seguridad, portabilidad, mantenibilidad, funcionalidad) establecidos para el proyecto.','Tecnologias de la información y las comunicaciones (TIC)','LIDER DE PROYECTO','')
,(215,'ADMINCXP','Táctico 2','ADMINISTRADOR CUENTAS POR PAGAR','Nacional','Administrar, organizar y procesar toda la información relacionada con cuentas por pagar a proveedores, contratistas y demás obligaciones a cargo de la compañía','Tesoreria','JEFE DE TESORERIA','')
,(216,'ADMIARCH','Táctico 2','ADMINISTRADOR DE ARCHIVO','Nacional','Registrar, tramitar, organizar, conservar y recuperar la documentación de la empresa de acuerdo a las normas y leyes establecidas.','Gestión documental','DIRECTOR ADMINISTRATIVO Y FINANCIERO','')
,(217,'ANALCONS','Táctico 2','ANALISTA DE CONSTRUCCIONES','Nacional','Analizar datos, procesos y procedimientos establecidos para la construcción de instalaciones de la compañía.','Construcciones','JEFE NACIONAL DE CONSTRUCCIONES','')
,(218,'ANALCREC','Táctico 2','ANALISTA DE CREDITO Y CARTERA','Nacional','Planear, participar y ejecutar las actividades necesarias para el cumplimiento de las metas trazadas dentro del proceso de cartera y que contribuyan al logro de los objetivos de la organización.','Cartera','JEFE DE CARTERA','')
,(219,'ANALFACT','Táctico 2','ANALISTA DE FACTURACION','Nacional','Efectuar el análisis del comportamiento de los consumos y total de usuarios de la compañía, a fin de generar alarmas y propuestas de intervención para la toma de decisiones mediante informe.','Facturación','JEFE DE FACTURACION','')
,(220,'ANALOPER','Táctico 2','ANALISTA DE OPERACIONES','Nacional','Asegurar el estricto cumplimiento en la atención de emergencias y PQR generada en los sistemas de distribución de gas natural de la compañía, garantizando los tiempos y responsabilidades acorde con la normatividad legal vigente. Así mismo apoyará las actividades logísticas necesarias para garantizar la continuidad del servicio en los sistemas de
GNC.','Central de operaciones','COORDINADOR CENTRAL OPERACIONES','')
,(221,'ANALPLAN','Táctico 2','ANALISTA DE PLANEACION','Nacional','Colaborar con el área de planeación en los diferentes análisis y tareas para el logro de los objetivos trazados por el área.','Planeación y regulación','JEFE DE PLANEACION','DIRECTOR ADMINISTRATIVO Y FINANCIERO')
,(222,'ANALPROY','Táctico 2','ANALISTA DE PROYECTOS','Nacional','Generar soporte en el manejo de los recursos designados por la compañía para alcanzar los objetivos de los proyectos en calidad, costo y oportunidad, teniendo un excelente relacionamiento con clientes internos y externos.','Planeación y regulación','JEFE DE PLANEACION','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(223,'ANALISOC','Táctico 2','ANALISTA DE SALUD OCUPACIONAL','Nacional','Desarrollar estrategias destinas a prevenir, proteger y atender a los trabajadores de los efectos de las enfermedades y los accidentes, que puedan ocurrir con ocasión o como consecuencia del trabajo, mediante programas de Medicina Preventiva y del Trabajo, vigilancia Epidemiológica y Riesgo Psicosocial.','HSEQ','JEFE DE HSEQ','')
,(224,'ANALISOL','Táctico 2','ANALISTA ISOLUCION','Nacional','Ejecutar, coordinar y promover los módulos de la plataforma ISOLUCION, asesorando y garantizando el cumplimiento de los parámetros establecidos en la plataforma para el logro de la misión y objetivos, con eficiencia, eficacia y efectividad.','Control interno','JEFE DE CONTROL INTERNO','JEFE DE HSEQ')
,(225,'ANALJURI','Táctico 2','ANALISTA JURIDICO','Nacional','Colaborar con el Director Jurídico frente a los procesos que se realizan a favor y en contra de la empresa y la realización de labores encomendadas.','Dirección jurídica','JEFE JURIDICA','')
,(226,'ANASERCL','Táctico 2','ANALISTA SERVICIO AL CLIENTE','Nacional','Garantizar el soporte al área de Servicio al Cliente en la elaboración y análisis de reportes, indicadores, informes y actividades de seguimiento y control.','Servicio al cliente','JEFE SERVICIO AL CLIENTE','')
,(227,'ANALSERA','Táctico 2','ANALISTA SERVICIOS ASOCIADOS','Nacional','Analizar datos, procesos y procedimientos establecidos para el cumplimiento de actividades alcance de servicios asociados, control pérdidas, suspensiones y reconexiones.','Servicios asociados','JEFE NACIONAL DE SERVICIOS Y CONTROL','')
,(228,'ANALSST','Táctico 2','ANALISTA SST','Nacional','Garantizar un ambiente laboral seguro, mediante el control de causas básicas que potencialmente puedan generar enfermedades laborales o accidentes de trabajo.','HSEQ','JEFE DE HSEQ','')
,(229,'ANATECAD','Táctico 2','ANALISTA TECNICO ADMINISTRATIVO','Nacional','Establecer planes, instructivos procedimientos, registro y controles de obra de actividades que están ligadas a la construcción de Redes, instalaciones, servicio, y mantenimiento, que son desarrollada por empresa contratistas y/o funcionarios de la organización.','Dirección técnica','DIRECTOR TECNICO','')
,(230,'AUDISIST','Táctico 2','AUDITOR DE SISTEMAS','Nacional','Garantizar que las actividades de auditoria interna se realicen de forma sistemática y oportuna para asegurar la calidad del diseño y ejecución de las auditorias, los controles generales de TIC, incluyendo infraestructura tecnológica y gestión de seguridad, con el fin de contribuir al desarrollo eficiente y eficaz de los procesos y a la optimización de los resultados de la Compañía.','Auditoria','JEFE DE AUDITORIA INTERNA','')
,(231,'AUDTCNI','Táctico 2','AUDITOR TECNICO CONTROL INTERNO I','CentroOperativo','Asesorar, promover, coordinar y evaluar la implementación y funcionamiento del Sistema de Control Interno en los procesos, recomendando las acciones de mejoramiento continuo, para el logro de la misión y objetivos institucionales, con eficiencia, eficacia y efectividad.','Control interno','JEFE DE CONTROL INTERNO','')
,(232,'AUDTCIII','Táctico 2','AUDITOR TECNICO CONTROL INTERNO III','CentroOperativo','Validar, asesorar y promover la implementación y funcionamiento del Sistema de Control Interno en los procesos, desarrollando validación de las actividades de control, para el logro de la misión y objetivos institucionales, con eficiencia, eficacia y efectividad.','Control interno','JEFE DE CONTROL INTERNO','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(233,'INGSOFTO','Táctico 2','INGENIERO DE SOFTWARE 1','Nacional','Participar integralmente en el análisis, diseño, desarrollo y mantenimiento de los sistemas de información de la Compañía, de acuerdo a las políticas y estándares establecidos y en pro del beneficio de los clientes y funcionarios.','Desarrollo y soporte','COORDINADOR DESARROLLO Y SOPORTE','')
,(234,'INGESOPO','Táctico 2','INGENIERO DE SOPORTE','Nacional','Contribuir de manera integral con las áreas de negocio de la Compañía en el funcionamiento de los Sistemas de Información, con el fin de asegurar su correcta operatividad.','Desarrollo y soporte','COORDINADOR DESARROLLO Y SOPORTE','')
,(235,'INTEADM','Táctico 2','INTERVENTOR ADMINISTRATIVO','Nacional','Elaborar el seguimiento a Contratistas en el cumplimiento de las Obligaciones Contractuales','Interventoria','JEFE DE INTERVENTORIA','')
,(236,'INTESISO','Táctico 2','INTERVENTOR SISO','Nacional','Validar que los Contratistas de Alcanos de 
Colombia cuenten con un ambiente laboral 
seguro, mediante el control de causas básicas 
que potencialmente puedan generar 
enfermedades profesionales o accidentes de 
trabajo.','Interventoria','JEFE DE INTERVENTORIA','')
,(237,'PROFCARJ','Táctico 2','PROFESIONAL CARTERA JUNIOR','Nacional','Planear, participar y ejecutar las actividades necesarias para el cumplimiento de las metas trazadas dentro del proceso de cartera y que contribuyan al logro de los objetivos de la organización','Cartera','JEFE DE CARTERA','')
,(238,'PROFCPER','Táctico 2','PROFESIONAL COMERCIALIZACION DEGAS','Nacional','Gestionar táctica y operativamente la optimización de las Compras-Costos y las Ventas a Grandes Clientes (Industrias y GNCV), de suministro y/o transporte de gas natural; y Masificar las ventas en el Mercado Secundario, generando beneficio a todos los grupos de interés de la compañía. Aportar al Jefe de Comercialización de gas con mejoramiento de los procesos y el equipo de trabajo.','Comercialización de gas','JEFE COMERCIALIZACION DE GAS','')
,(239,'PCONPERD','Táctico 2','PROFESIONAL CONTROL PERDIDAS','Nacional','Contribuir en la recuperación de los valores de la empresa por concepto de cobros por investigación, resultado de las anomalías que se encuentren en equipos de medición, redes y acometidas atribuibles al usuario que generan pérdidas de gas natural.','Control pérdidas','LIDER NACIONAL CONTROL PERDIDAS','')
,(240,'PROCOORG','Táctico 2','PROFESIONAL DE COMUNICACION','Nacional','Promover y difundir de manera interna y externa la información que representa y compromete a la compañía mediante el diseño, mantenimiento y control de los medios de comunicación necesarios empleando actividades como free press, mercadeo y relaciones públicas.','Dirección comercial','DIRECTOR COMERCIAL','')
,(241,'PROFGNCV','Táctico 2','PROFESIONAL GNCV Y CRM','Nacional','Gestionar tácticamente y/o operativamente las contrataciones y nominaciones de compras y/o las ventas a Grandes Clientes (GNCV), de suministro y/o transporte de gas natural. Gestionar táctica y operativamente el Programa Bono Vehicular y el Programa CRM a los diferentes clientes de la compañía. Aportar a la Jefatura de Comercialización de gas con mejoramiento de los procesos y el equipo de trabajo.','Comercialización de gas','JEFE COMERCIALIZACION DE GAS','')
,(242,'PROTCAPD','Táctico 2','PROFESIONAL TEC CAPACITACION Y DESAROLLO','Nacional','Diseñar, desarrollar e implementar el programa de capacitación orientado a la formación especializada de personal en el sector gas y otros, que garanticen la competencia laboral de acuerdo al cargo establecido en la empresa.','Capacitación y desarrollo','DIRECTOR DE GESTION HUMANA','')
;
INSERT INTO util.TemporalCargo (Id,Codigo,NivelCargo,Nombre,Clase,ObjetivoCargo,Dependencia,CargoJefeInmediato,OtroCargoReporta) VALUES 
(243,'ANALVENT','Táctico 2','ANALISTA DE VENTAS','Nacional','Informar a la Dirección Comercial datos que permitan conocer las oportunidades, amenazas, fortalezas y debilidades en cada uno de los segmentos del mercado y zonas futuras para la comercialización y distribución del servicio.','Mercadeo y ventas','JEFE DE VENTAS','')
,(244,'PROFCONS','Táctico 2','PROFESIONAL CONTABLE NIFF SENIOR','Nacional','Analizar, preparar, revisar, organizar, elaborar y presentar información contable y financiera según los direccionamientos, requerimientos y demás normatividad vigente emitida por los organismos de regulación, vigilancia y control.','Contabilidad e impuestos','JEFE DE CONTABILIDAD','')
;